### ISSUE TITLE
Sappy Seed should not be bounced back by Magic bounce

### ISSUE THREAD

**Issue by WwlWss** [smogon/pokemon-showdown#10292]
![Image_1715418668890](https://github.com/smogon/pokemon-showdown/assets/90305844/48a618ca-82a5-44b3-8a79-14cb78e8a806)
I observed this phenomenon in Broken Cup Metagames. Although Sappy Seed only exists in LGPE, which works without Ability, it is not a non damaging move and should not be bounced back by the Magic Bounce, It should work like Stone Axe.

**Comment by urkerab** [comment]
Data mining shows that Sappy Seed has the Reflectable flag, even though there isn't any way of reflecting it in LGPE.

https://www.smogon.com/forums/posts/10029941
