### ISSUE TITLE
Incorrect description of Sand Veil

### ISSUE THREAD

**Issue by jbmagier** [smogon/pokemon-showdown#10475]
This should read that accuracy is .8x on the Pokemon if it's being perfectly correct.

https://github.com/smogon/pokemon-showdown/blob/d71cb04ae568cea7f434cdf7ea675f0abff6b624/data/text/abilities.ts#L1539

**Comment by DaWoblefet** [comment]
If it was being perfectly correct, it would report 3277/4096. There isn't [really a distinction between accuracy/evasion modifiers](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8684263) in this way; the games themselves report as "Boosts the Pokémon's evasiveness in a sandstorm.", so it's not unreasonable to report it as evasion in the description here. 1/1.25 = 0.8, so there's no real distinction here, unless you want to report every accuracy/evasion modifier as just an accuracy modifier.

There is an inconsistency in reporting accuracy or evasion between the long description and the short description for Sand Veil though (and other moves too, like Gravity). If someone wants to correct those inconsistencies, more power to them.

**Comment by Marty-D** [comment]
The reason for any inconsistencies is there is no space in the short descriptions to match the long one.
