### ISSUE TITLE
Mismatched minimum Node.js version in server/README vs build

### ISSUE THREAD

**Issue by larry-the-table-guy** [smogon/pokemon-showdown#10535]
[The installation instructions for the server](https://github.com/smogon/pokemon-showdown/blob/master/server/README.md#installing) lists v14+, but the [build script](https://github.com/smogon/pokemon-showdown/blob/master/build#L8) seems to expect v16+.

**Comment by asingh04** [comment]
In the [package.json](https://github.com/smogon/pokemon-showdown/blob/073db5ee384c8bf1c962636ff0b7755dc023622c/package.json#L31), it needs at least v14. So maybe we need to update this as well.

**Comment by asingh04** [comment]
I have created a PR for it #10672 
For node version upgrade for the whole repo/project, i think a separate PR would be needed
