### ISSUE TITLE
archaludon sprite missing

### ISSUE THREAD

**Issue by s0urce-c0de** [smogon/pokemon-showdown#10537]
![image](https://github.com/user-attachments/assets/2bd9b171-ece1-4122-b39d-d79d28761ba5)
https://play.pokemonshowdown.com/sprites/dex/archaludon.png
https://play.pokemonshowdown.com/sprites/dex-shiny/archaludon.png

**Comment by DaWoblefet** [comment]
This was cross-posted on our bug reports forum; https://www.smogon.com/forums/threads/sprite-issues-megathread.3734623/post-10263718
