### ISSUE TITLE
Turn Order needs to be handled how it is in-game

### ISSUE THREAD

**Issue by DanUgore** [smogon/pokemon-showdown#1157]
Mostly relevant to VGC and Triples. At the moment it is done using a sorting function which compares two pokemon at a time while ordering based on speed.
Properly handling this issue will involve:
- determining turn order before any moves are played out
- sorting the pokemon based on the in-game sort function. this includes using `speed & 8191` over `speed` for comparisons.
- using the battle's rng -- `this.random()` -- to determine speed-ties

This will also allow us to not require `getStatCallback()` for the "Trick Room Glitch"

**Comment by bb010g** [comment]
bump

**Comment by ascriptmaster** [comment]
What was the Trick Room Glitch?

**Comment by Slayer95** [comment]
https://www.youtube.com/watch?v=TmZHKZJMnBc

**Comment by ascriptmaster** [comment]
I noticed recently in `comparePriority` that there's code to check sub-priorities as well. Could we fashion out some sort of `ModifySubPriority` that Trick Room can use instead of mucking with speed?

**Comment by DanUgore** [comment]
https://github.com/DanUgore/Pokemon-Showdown/blob/turn-order/battle-engine.js#L3181

Here's an example @ascriptmaster Just have Trick Room modify decision.speed and not decision.pokemon.speed

**Comment by ascriptmaster** [comment]
That works too. `ModifyDecisionSpeed`?

**Comment by DanUgore** [comment]
Sure.

**Comment by DanUgore** [comment]
Speed is compared...
1) Before the turn plays out
2) After Mega Evolution (still uses pre-mega evolution speed. its just the order that the mega evolution occurs)
3) Before residuals (since mega evolution has already occurred it uses that speed)

Determining who wins a speed tie
1) Make a list of tied pokemon in order. Host (P1) Position A (left) would be the start (0), P2/P4 Position C (right) would be the end.
2) Roll a number between `0` and `tied_pokemon_total - 1`. Put that position to go first.
3) Repeat 2 while decrementing until `tied_pokemon_total == 1` and add the final pokemon to the end

**Comment by Zarel** [comment]
Wait, that's known? Do you have a link?

**Comment by Zarel** [comment]
Also, what happens in the case of multiple speed ties?

**Comment by DanUgore** [comment]
I don't have a link. I was talking with Kaphotics about the behavior back when I was working in the issue and needed to know how it worked. Also what do you mean by multiple speed ties? I don't see how that would cause different behavior.

**Comment by Zarel** [comment]
Depending on how Game Freak implements multiple speed ties, this could work completely differently in that case.
