### ISSUE TITLE
Friend list

### ISSUE THREAD

**Issue by TheImmortal** [smogon/pokemon-showdown#1736]
Self-explanatory. An old implementation can be viewed at #607 and Zarel/Pokemon-Showdown-Client#126.

**Comment by Zarel** [comment]
Current plan is to do this server-side with SQLite.

**Comment by Zarel** [comment]
#2762 was closed, but the idea of being able to follow a friend and see battles from their perspective is interesting and should be noted here.

**Comment by acz13** [comment]
Is the client label on this still true?

**Comment by Zarel** [comment]
There's obviously going to be a client component.

**Comment by marzdude9** [comment]
So has this been implemented yet?

**Comment by Zarel** [comment]
no, still in progress

**Comment by acz13** [comment]
Wouldn't it make more sense for this to be implemented with the auth server? Registered nicks exist between servers, after all.

**Comment by Zarel** [comment]
The problem is that it's not currently possible to PM people across servers, and the login server doesn't know whether or not you're online. In general, doing it in the sim server means there's a lot less lag because you don't need multiple servers to coordinate with each other.
