### ISSUE TITLE
Offline messaging

### ISSUE THREAD

**Issue by Zarel** [smogon/pokemon-showdown#2151]
Relatively high up on my to-do list is still offline messaging.

Related is supporting loading recent messages when logging into PS.

Rough sketch of architecture:
- PMs will be moved into a separate `pm.js`
- User objects will store the last ~10 (maybe 20 or more for staff) PMs sent or received
- These stored PMs will be replayed upon connecting to PS, like roomlogs
- To better support name changes in the middle of a conversation, name changes will accompany PM data; the client will store (and send) both the last sent and received username
- Truly offline PMs will ask for a confirmation, which, if accepted, will use a different command - `/offlinepm`?
- The server will store truly offline PMs in long-term storage (tentative: `config/offlinepm.tsv`, structured `date,source,target,message`)
- Offline PMs will be retrieved and used to populate stored PMs on connection
- "Report" button will show the user's stored PMs to a moderator (perhaps with a popup).

If any of you want to do these without me, feel free. Please do them a few steps at a time, so we don't end up with huge pullreqs that are difficult to approve.

**Comment by Joimer** [comment]
I think SQLite could be cool for this feature, as it is still a file, it's an npm install and probably better to manage than a tsv that can get really, really huge. LokiJS is another DB that could be useful for this.

**Comment by Zarel** [comment]
We decided against SQLite for the ladder because it turns out it's not just an npm install on Windows. :(

Do you think it'll get too huge to manage in tsv format?

**Comment by Zarel** [comment]
LokiJS, on the other hand, looks pretty promising. I'll have to look much closer at it. Too bad I already wrote the TSV database for the ladder. :(

**Comment by Zarel** [comment]
After investigation: LokiJS seems like it's a key-value store, using it like a ladder database is very low-performance. I guess I'll be sticking with my TSV solution for the ladder.

**Comment by Joimer** [comment]
I didn't know it was difficult to install SQLite on Windows. Too bad! Maybe LokiJS can work in this case (offline PMs), for sure it's going to be too low-performance for ladder, though. I reckon it can get quite big and slow to deal with a tsv, think of all the users constantly PMing.

Another option is to make it an opt-in for Windows servers... SQLite is so good to deal with this things!

**Comment by Zarel** [comment]
![](http://d.pr/i/s71N/lioTeOgP+)

Wow, their documentation has black text on a black background... I bet you can't read what the return value of this function is.

On the other hand, turns out they do support reasonably optimized sorts. It's starting to look workable for ladder databases, too...

**Comment by kotarou3** [comment]
:+1: for SQLite

If you're trying to run the server on Windows, you should already know, or be willing to work out yourself, how to install a compatible compiler...

**Comment by Joimer** [comment]
To be honest, if you are willing to run a server on Windows (!!), you should be able to get anything working, when possible. However, LokiJS has proven quite good, uses json so its data and API are easily understandable and can be reused, and it's an npm install away from everywhere. I think it could work for both ladder (I guess to be commented elsewhere) and this.

As for the issue at hand, I think the steps/PRs should be:
-Move PMs to pm.js
-Store PM data in user objects and, retrieve those when a user logs in, just like room logs.
-Store offline PMs in long-term storage and relay them to users when necessary.
-Add PM report button.

**Comment by Zarel** [comment]
These all sound good so far.

**Comment by panpawn** [comment]
Has anyone thought of cross-server offline messaging?  For the users that frequent several servers, it could be a neat idea to have this.

Some downsides to this is obviously a much bigger database and more load, but if it could be worked out then that would be amazing!

**Comment by AustinXII** [comment]
A lot of other servers already implemented a version of offline messaging. For example they already have it so a message will appear to you once you return to that server.

**Comment by panpawn** [comment]
Right, but I'm referring to if ``x`` user send a tell to ``y`` on ``z`` server, they will get it if they go on ``q`` server before ``z`` server.
... hence "cross-server"

**Comment by Zarel** [comment]
A generalized cross-server PM system would be interesting, and I've actually thought about it a lot. The main disadvantage is that it would make the "report" feature I was planning on a _lot_ harder to implement.

**Comment by panpawn** [comment]
Ah yea, that's true - hit and run instances would probably occur a lot more and it would be harder to track them down.

**Comment by acz13** [comment]
This reminds me of an monotype server that had the /tell command... I think it used MongoDB?

**Comment by TheFenderStory** [comment]
We used MongoDB for an offline messaging system along with storing other information. We began experiencing a significant amount of lag reading data from the bson it stored to. I would recommend mysql for this project.

**Comment by acz13** [comment]
Oh, ok Fender... +1 for MySQL then.

**Comment by Zarel** [comment]
lol, we pushed this off long enough for SQLite to be a feasible backend for this.

**Comment by panpawn** [comment]
What's the status on this, @Zarel?

**Comment by Zarel** [comment]
In progress.

**Comment by acz13** [comment]
have we decided a backend for this?

**Comment by Zarel** [comment]
Yes, the backend is to be SQLite.

**Comment by panpawn** [comment]
>PMs will be moved into a separate pm.js

Is this part still wanted?

**Comment by panpawn** [comment]
I might be wrong, but it looks like SQLite does not support node v6.x :|

**Comment by Zarel** [comment]
Yes, moving into pm.js is still wanted, but no reason to do it without implementing any features that it would be better for.

**Comment by acz13** [comment]
@panpawn https://github.com/mapbox/node-sqlite3 ???

`The sqlite3 module works with Node.js v0.10.x, v0.12.x, v4.x, v5.x, v6.x and v7.x.`

**Comment by AlainDuhHero** [comment]
@Zarel I was thinking to join this Project 
Could u sum up what I need to keep in mind when I am doing it?

**Comment by Zarel** [comment]
no, please don't.

**Comment by Zarel** [comment]
I should maybe post a sketch of the current plan here.

So firstly, we need to abstract out scrollback/log storage for rooms. Get used to log retrieval being async.

After that's done, we can have separate backends for scrollback storage (because Node maxes out at like 2GB of RAM usage), such as Redis (my current choice).

Redis will allow us to stuff a lot more data into it (still needs to be kept in RAM, but I'm looking at something like ~16GB of storage, which is fine), so we would then have room to have longer room scrollback, to persist it through restarts, and to add PM logs into it.

**Comment by panpawn** [comment]
So, what about the GUI refactor of PMs?  Are they going to look different, if so how? Will there be a PM-tab bar, like the room-tab bar?

**Comment by Zarel** [comment]
UI would look the same but maybe have added features.

**Comment by Zarel** [comment]
Hm, apparently recent versions of V8 have lifted the 1.4GB memory limit? Google doesn't give very many details.

If so, we might not need Redis. We could just keep everything in memory. We'd still need some way to write the data to disk to persist it between restarts, though. SQLite?

Our _main_ issue is that apparently there aren't very many good ways to have a long-term key-value store where the value is resizable data that frequently resizes. @scheibo, any ideas?

**Comment by scheibo** [comment]
This seems like the type of feature which would benefit from a design doc going over the current solution and scale of messaging today, complications (name changes, different servers etc), the proposed options and requirements. I don't think I understand the full scope at this point to be able to weigh in.

I have trouble believing a standard SQL database like Postgres or MySQL wouldn't work for messaging for a service of PS!'s size (with SQLite there are concurrent write issues that might be more trouble to work around - I think with the ladder/logs/replays itd be more viable because you could shard DBs per format). If we were 10x larger, starting to look at something like Cassandra would probably be logical, but from my experience maintaining a large Cassandra database in the past it was significantly more work (though that was 7 years ago and I'm sure the landscape has changed). I also have trouble believing the ladder couldn't be made to work with a relational database - I imagine there are probably some indices/schema changes/other optimizations that are probably missing if there are issues.

> where the value is resizable data that frequently changes

I'm confused about what the keys and values are here? And why we want to bother storing anything in memory - why wouldn't we write the PMs to a database/file and then when a user comes online we read it back into memory?

**Comment by Zarel** [comment]
> I have trouble believing a standard SQL database like Postgres or MySQL wouldn't work for messaging for a service of PS!'s size (with SQLite there are concurrent write issues that might be more trouble to work around - I think with the ladder/logs/replays itd be more viable because you could shard DBs per format). If we were 10x larger, starting to look at something like Cassandra would probably be logical, but from my experience maintaining a large Cassandra database in the past it was significantly more work (though that was 7 years ago and I'm sure the landscape has changed). I also have trouble believing the ladder couldn't be made to work with a relational database - I imagine there are probably some indices/schema changes/other optimizations that are probably missing if there are issues.

I _also_ have trouble believing a standard SQL database wouldn't work for PS, because we don't have any mindboggling high numbers. We're just using millions and gigabytes. I _personally_ always thought "big data" meant "too big to fit in RAM".

Nonetheless, the only thing that matters is results, and the results say that we've never had a single database not start to break down after we put a few gigabytes of data into it. I've fiddled with schemas (mainly, switching everything from text columns to binary columns, in case it's something to do with text normalization), and literally every query we do is fully indexed (after our latest schema change, the auto-index-use broke down and I had to manually add `USE INDEX` to make the queries fast again, which is weird because they were _very_ straightforward `SELECT`s, no `JOIN`s or anything remotely weird).

Literally the most complicated query we do is `SELECT * WHERE formatid = $ ORDER BY elo` with a `formatid,elo` index.

We're using InnoDB, I've run mysqltuner and done everything it recommends... if you want to take a look, seriously be my guest.

Everyone who's ever taken a look says "idk, everything _should_ be fine". One of my guesses is a hard drive failure but idk how to _check_ that.

> I'm confused about what the keys and values are here? And why we want to bother storing anything in memory - why wouldn't we write the PMs to a database/file and then when a user comes online we read it back into memory?

The keys would be `roomid` (which for PMs would be `pm-[userid1]-[userid2]`) and the values would be `log` (`\n`-delimited protocol log). Storing things in a `Map<string, Buffer>` has the advantage that accessing them is atomic, so you don't have to worry about race conditions (if a user gets a PM while loading old PMs from disk, you have to write a lot of code to make sure they get displayed in the right order).
