### ISSUE TITLE
Ho Oh is restricted to event-only movesets

### ISSUE THREAD

**Issue by SivanMehta** [smogon/pokemon-showdown#2322]
### Recreating

Currently when I try the "validate" button with following set, [which directly from the smogon website](http://www.smogon.com/dex/xy/pokemon/ho-oh/) I am given an error

```
Ho-Oh @ Choice Band
Ability: Regenerator
EVs: 248 HP / 196 Atk / 52 SpD / 12 Spe
Adamant Nature
- Brave Bird
- Sacred Fire
- Earthquake
- Sleep Talk
```

Here is the rejection:

```
Ho-Oh is only obtainable via event - it needs to match one of its events.
```
### Possible sources

Right now, it seems [this](https://github.com/Zarel/Pokemon-Showdown/blob/1d7c356947303920308cf01590bba7e9ceb4604d/team-validator.js#L496) clause is picking up Ho Oh as an event-only pokemon, while in reality it can be obtained in X&Y via Pokébank.

**Comment by sirDonovan** [comment]
@SivanMehta which format?

**Comment by SivanMehta** [comment]
@sirDonovan Ubers

**Comment by TheImmortal** [comment]
I copy/pasted that exact set and it works fine - "Your team is valid for Ubers."

The only explanation I have is that you're trying to use a shiny Ho-Oh. The Regenerator event is non-shiny.

**Comment by SivanMehta** [comment]
Well then, I guess it was the shininess that was throwing it off.

**Comment by TheImmortal** [comment]
In any case, I improved the error message: 9d99142dd8744bc19a354a2332bea8943e664f07
