### ISSUE TITLE
Can not recover a lost password.

### ISSUE THREAD

**Issue by Muhznit** [smogon/pokemon-showdown#273]
Logins are said to be integrated with the forum. However, using the email I usually use for my passwords, I can not recover my password through any process whatsoever.

**Comment by gary-host-laptop** [comment]
> While this is a legitimate bug, this is a client issue, so I'm closing this because it doesn't belong here.

Hello, could I open an issue asking for adding some sort of e-mail verification client side for Pokemon Showdown or it is not planned?

**Comment by mia-pi-git** [comment]
> > While this is a legitimate bug, this is a client issue, so I'm closing this because it doesn't belong here.
> 
> Hello, could I open an issue asking for adding some sort of e-mail verification client side for Pokemon Showdown or it is not planned?

It is planned, and in progress, but this isn't the place for that anyway.
