### ISSUE TITLE
Polls: Supporting multiple votes per user

### ISSUE THREAD

**Issue by panpawn** [smogon/pokemon-showdown#3696]
Sometimes, a room might ask you to select several options out of many to answer a question.

Example question: Which of these games do you own?
Possible answers: GTA, CS:GO, Dota 2, Minecraft

Right now, if you wanted to as an equivalent question on PS with the poll system, you would have to create joined answers which it doesn't support enough for this and that's a lot more effort on the poll creator.  It also would be presented better if the options weren't grouped as well.

Ideally, this should be an opt-in option per poll creation.

**Comment by bumbadadabum** [comment]
For polls with 8 or less options I don't really see this having much of a beneficial effect.

**Comment by Zarel** [comment]
I guess you could have Font Awesome checkboxes on the options. "View results" would lock in your answers.

**Comment by Zarel** [comment]
It might be worth it?

**Comment by AustinXII** [comment]
I think it's worth it

**Comment by DeathlyPlays** [comment]
This would be cool ngl

**Comment by Zarel** [comment]
I believe this was implemented by @whalemer some time ago?
