### ISSUE TITLE
Current modlog issues

### ISSUE THREAD

**Issue by panpawn** [smogon/pokemon-showdown#4622]
Modlog currently has a few issues, some semi-new and some not that really make it harder than it has to be to use.

- The format of modlog entries was semi-recently changed, and the script to convert old entries was never used. This makes entries in the modlog hard to search for, as there's one format for before the change and one for after. Backwards compatibility should have been more deeply considered.
- ``/modlog`` in a room with no arguments should show the most recent modlog entries like it used to, but its not.  (A current walk around is using ``/modlog *`` in the room... @sparkychildcharlie ...)
- ``/modlog all, [search]`` used to include searches of the global modlog, but it seems this is no longer the case. This makes searching for global stuff more complicated than it has to be, as it then can require 2 separate searches. Also, this change in behavior was never documented on the UI help commands (or anywhere, from what I can tell...)
- The only way to search the global modlog is to use ``/modlog [search]`` in the staff room. There could definitely be an easier way to do this. (i.e., ``/modlog global, [search]``)

(If I think of more issues, I'll edit-add them to this list)

**Comment by sparkychildcharlie** [comment]
Thanks! I'll get to this as soon as I can

**Comment by Zarel** [comment]
I have the conversion script, I just haven't had the time to proofread and run it yet.

**Comment by Zarel** [comment]
I don't think the awkward mid-phase is all that big of a deal? It definitely can't be done before merging in the changes, because then you'd have a set of logs in the old format, from after the conversion but before the changes were merged and hotpatched in.

**Comment by AnnikaCodes** [comment]
> The format of modlog entries was semi-recently changed, and the script to convert old entries was never used. This makes entries in the modlog hard to search for, as there's one format for before the change and one for after. Backwards compatibility should have been more deeply considered.

This is going to be fixed in #7403.

> /modlog in a room with no arguments should show the most recent modlog entries like it used to, but its not. (A current walk around is using /modlog * in the room... @ sparkychildcharlie ...)

This is no longer an issue.

> /modlog all, [search] used to include searches of the global modlog, but it seems this is no longer the case. This makes searching for global stuff more complicated than it has to be, as it then can require 2 separate searches. Also, this change in behavior was never documented on the UI help commands (or anywhere, from what I can tell...)

Is this still desired functionality? AFAIK, most global modlog entries are associated with a room.

> The only way to search the global modlog is to use /modlog [search] in the staff room. There could definitely be an easier way to do this. (i.e., /modlog global, [search])

This is no longer an issue; use `/modlog global, `.
