### ISSUE TITLE
Add a Pokémon box feature

### ISSUE THREAD

**Issue by AffanIndo** [smogon/pokemon-showdown#4718]
On the past I've played competitively on Pokemon Online and they had this feature where you could store your pokemon.

https://orig00.deviantart.net/44b8/f/2011/285/0/5/pokemon_online___god_box_by_sasukesfriend-d4coapt.png

I think this is a good feature because you could store individual pokemon with different moveset in separate slot, instead of creating a whole new team. For example you can store 5 different Charizard moveset, so instead of creating a new team, just pull the pokemon box and then withdraw the charizard with moveset that you want.

**Comment by Zarel** [comment]
I'd be surprised if we didn't already have a ticket for this.

**Comment by MacChaeger** [comment]
This should really be a client issue, but could this be implemented as simply extra-large teams in the teambuilder, in 4 rows of 6 for a total of 24, the maximum number of Pokemon allowed on one team in a custom game?

**Comment by MacChaeger** [comment]
Something like this? http://prntscr.com/mbrsyf

**Comment by MacChaeger** [comment]
I changed it up and went for the idea of just having a special folder for boxes, which lets players assign formats to them instead of being able to group them in their own folders, and I'm pretty much done except for the part where I enforce every player having a `'Boxes'` folder. That part's got me pretty stuck, though.

**Comment by mk360** [comment]
@MacChaeger any update on this issue?

**Comment by Th-eo** [comment]
A small bump on this issue. It's annoying to have identical teams except for one-two Pokémon because you're trying different stuff out.

**Comment by Zarel** [comment]
Implemented in https://github.com/smogon/pokemon-showdown-client/pull/1222
