### ISSUE TITLE
Illegal moves in RBY/GSC randbats data

### ISSUE THREAD

**Issue by Slayer95** [smogon/pokemon-showdown#5337]
- [x] [gen2] PERSIAN: Move 'icebeam' cannot be learnt
- [x] [gen2] TYPHLOSION: Move 'counter' cannot be learnt
- [x] [gen2] NOCTOWL: Move 'doubleedge' cannot be learnt
- [x] [gen2] LEDIAN: Move 'substitute' cannot be learnt
- [x] [gen2] JUMPLUFF: Move 'substitute' cannot be learnt
- [x] [gen2] AIPOM: Move 'substitute' cannot be learnt
- [x] [gen2] GIRAFARIG: Move 'substitute' cannot be learnt
- [x] [gen2] HOUNDOOM: Move 'substitute' cannot be learnt
- [x] [gen1] ZUBAT: Move 'screech' cannot be learnt
- [x] [gen1] OMANYTE: Move 'seismictoss' cannot be learnt

**Comment by TheImmortal** [comment]
@xCrystal

**Comment by Slayer95** [comment]
They are inactive in Github since September...

**Comment by TheImmortal** [comment]
Uh, @ascriptmaster then.

**Comment by Slayer95** [comment]
Gen 1 issues introduced in 892719ddbe2. There was no set information before.
Gen 2 issues introduced from 07bbdd0ab9 onwards. Set information before [here](https://github.com/Zarel/Pokemon-Showdown/blob/85c83be66685c436995bbc1a4df472401f5a8e74/mods/gen2/formats-data.js).

**Comment by TheImmortal** [comment]
Gen 1 fixed in 99caab2

**Comment by scheibo** [comment]
Was about to close, but unless I'm missing something, Gen 2 Houndoom still needs fixes? @mark7328?
