### ISSUE TITLE
Z-memento should heal mons even if the stat drop does not resolve

### ISSUE THREAD

**Issue by MBC1215** [smogon/pokemon-showdown#5494]
In the replays posted below, z-memento does NOT heal replacements HP after interacting with clear body. This is not supposed to happen, as stated on bulbapedia, "If powered up by a Darkinium Z into Z-Memento, if a Pokémon is switched in to replace the user the same turn, that Pokémon has its HP fully restored (even if Z-Memento was not used successfully after gaining its Z-Power effect)." This is a pretty big issue, as it could very easily sway games because not only is a Z move burned, but absolutely nothing happens with the z-move.

Replays: http://replay.pokemonshowdown.com/gen7ru-900826580   http://replay.pokemonshowdown.com/gen7customgame-906660990

**Comment by Zarel** [comment]
Why was this closed? Did you learn this was mistaken?

**Comment by scheibo** [comment]
They opened https://github.com/Zarel/Pokemon-Showdown-Client/issues/1276 instead, but it seems like this is a server issue and not a client issue?

**Comment by Zarel** [comment]
I'll reopen this, then. Although is _probably_ isn't a bug. @Marty-D?

**Comment by Marty-D** [comment]
It's a bug; Parting Shot is also suddenly bugged even though it worked a few months ago and there's a test specifically for it: https://github.com/Zarel/Pokemon-Showdown/commit/06e03e34311d0d033c9ccdeacf9291102e40891f

**Comment by MBC1215** [comment]
Really sorry, i just didnt want to waste time and ended up wasting more of it. Thanks for getting on top of it tho, appreciate it.

**Comment by DaWoblefet** [comment]
Fixed in https://github.com/smogon/pokemon-showdown/pull/8591
