### ISSUE TITLE
Refactor `/server/team-validator-async.js` to Typescript

### ISSUE THREAD

**Issue by asingh04** [smogon/pokemon-showdown#5528]
The above mentioned file is to be migrated/refactor to `/server/team-validation-async.ts` file, using Typescript

**Comment by Zarel** [comment]
I suppose this is fine to announce you're working on this, but to be clear, it's not required. Do you know how long you'll take to make the PR?

**Comment by asingh04** [comment]
@Zarel  I will be able to dedicate to this on weekends (Saturdays & Sundays), so I think i should be able to come up with the PR after 2 weeks, as I have to go through and understand the conventions and procedure for writing the .ts file.

**Comment by AnnikaCodes** [comment]
This was done in #5987.
