### ISSUE TITLE
null vs undefined

### ISSUE THREAD

**Issue by Zarel** [smogon/pokemon-showdown#5643]
We've gotten some disagreement over whether or not to use `null` or `undefined` as our null value in the codebase, so let's hash it out here, instead of traumatizing first-time contributors' PRs with our arguing.

Note that this wouldn't apply to our battle engine, which uses both `null` and `undefined` to mean different things.

**Comment by Zarel** [comment]
Currently, the codebase mostly uses `null`.

`undefined` is longer to type, but it has the advantage that it can be replaced with a strategically-placed `?` in some (but not all) places.

`undefined` has a disadvantage where `foo.bar === undefined` can refer to two different possible states, with different performance implications and different behavior with `for..in`, `Object.keys`, and `Object.assign`.

**Comment by Zarel** [comment]
I'm overall relatively neutral to which we use, but I slightly prefer `null`, and a change _would_ involve making `git blame` harder to use.

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/blob/b06d638b6e317aaf2e278513eddb754f9dbd339e/server/room-battle.js#L183-L187

Example workaround for `undefined` weirdness.

**Comment by marwanpro** [comment]
I think `null` is a better.

Mixing null and undefined can lead to confusion when new contributor debug their code.

![](https://i.stack.imgur.com/T9M2J.png)

**Comment by varun1729** [comment]
Adding to this, `undefined` should only occur when variable names are mistyped. `null` makes more sense.

**Comment by Zarel** [comment]
We eventually settled on `null`, mostly, but allowing `undefined` if someone has a strong opinion about it.

The `null` vs `undefined` toilet paper analogy isn't useful to us because it's confusing to newcomers, adds very little, and it's widely agreed that having separate `null` vs `undefined` was a mistake in the first place.
