### ISSUE TITLE
Should there be a proper way to handle breaking changes to protocol?

### ISSUE THREAD

**Issue by Kaiepi** [smogon/pokemon-showdown#5794]
At the moment, any time there are breaking changes to protocol,  you need to search for any bots that may be using the feature that you're changing and fix them to work with the new protocol, if needed. Some bots don't even have their source code hosted anywhere, so it's not guaranteed you'll be able to find and fix every single bot.

Another issue is the official client needs to keep compatibility with both the old and new protocol every single time breaking changes happen, which prevents changes that completely break how types of messages are parsed from being possible to do at all.

Should there be a proper way to handle breaking changes to protocol? If so, how?

I think protocol should be versioned, but I'll wait until there's some confirmation that there should be a proper way before elaborating on how this could work. The way I have it planned out would ensure all clients can fully understand what the server sends them, regardless of whether or not they actually know how to specify what version of protocol they want.

**Comment by Zarel** [comment]
I'm mostly opposed to versioning, because so far we haven't seen a need for it. It's not like it eliminates the need to support old clients (bots) or old servers. I don't see it adding anything.

If a specific change requires versioning, we can consider it in the specific change.

**Comment by Zarel** [comment]
I think we probably should have some sort of mailing list or Discord server or _something_ so that we can notify relevant developers of protocol changes.

**Comment by Zarel** [comment]
A Discord server would be easy, we could just `@`everyone whenever we made breaking changes.

**Comment by scheibo** [comment]
I would expect serious developers to 'Watch' the repo to be aware of these changes, but I guess thats perhaps too much to ask? I'm not opposed to having a more formal process/way of notifying downstream developers of changes outside of simply posting in the RO forum or `<botdev>` like we did before the `/status` changes. I'd kind of prefer a mailing list or forum thread, but only because I feel like I'm already in enough Discord servers...

**Comment by Zarel** [comment]
I would expect a lot of bot devs not to be serious.

**Comment by bumbadadabum** [comment]
I don't like the idea of a discord server. Forum thread, github issue or just using the botdev room is good enough imo.

**Comment by scheibo** [comment]
While we've been rather dismissive so far as to the potential benefits, I'm curious about this:

> I think protocol should be versioned, but I'll wait until there's some confirmation that there should be a proper way before elaborating on how this could work. The way I have it planned out would ensure all clients can fully understand what the server sends them, regardless of whether or not they actually know how to specify what version of protocol they want.

**Comment by Kaiepi** [comment]
Late, but what how I was thinking protocol version could be implemented was with a version handshake. The server would send a `|version|` message containing the current version of protocol it supports as the first message it sends along with the initial block of messages it sends on connect. What happens afterwards depends on the client:

- Clients that don't support protocol versioning

These would ignore the `|version|` message sent. The server would assume all clients o use the first protocol version until they prove otherwise, so nothing would need to be done by either the client or the server.

- Clients that support protocol versioning

These would send `/version <version no.>` to the global room in response as their first message, with `<version no.>` being the latest version at or below the one the server sent that it supports. If the version received by the server is valid, set the connection's protocol version to this and use it from then on, otherwise the connection would be closed.

There are some downsides to how I thought this out though:

- types of messages included with the initial block of messages, like `|updateuser|`, would not be possible to make breaking changes to since there wasn't any other decent way I could think of to deal with clients that don't support versioning
- implementing this when there's no single place where all protocol is handled wouldn't exactly be pretty

**Comment by Kaiepi** [comment]
If protocol versioning wouldn't be a good way to deal with this, the only way of communicating with client developers I'd really support is a mailing list included in the README. Expecting people to go to `<botdev>` on main kind of goes against the idea of PS being open source if there's a one and true implementation, and certain types of people that use side servers would never want to go on main. Not everyone wants to use Smogon. Not everyone wants to use Discord. Not everyone wants to use Github, even. Everyone has e-mail, and everyone reads the README (hopefully) at some point while writing a bot though.

**Comment by Zarel** [comment]
It still seems to me like versioning solves a completely different problem than the one you're actually trying to solve.

We explicitly try to avoid needing to support multiple versions of the protocol, by making all changes backwards-compatible.

**Comment by Zarel** [comment]
Versioning is a backup plan for if changes can't be backwards-compatible, but we've yet to need such a change.

**Comment by Zarel** [comment]
We have a Discord server now, which can be subscribed to:

https://spo.ink/dev

I see no reason to keep this issue open. I don't think we've ever had a problem that versioning the protocol would solve, and if we ever do in the future, we can revisit the idea then.
