### ISSUE TITLE
Tour Break

### ISSUE THREAD

**Issue by kanmingxu00** [smogon/pokemon-showdown#5796]
Tournament disqualified player while he was in a game, he said he did not change his name or his device. I'll look into this this weekend, unless someone wants to take this.

**Comment by whalemer** [comment]
Do you have a roomlog link / user name / room name?

**Comment by kanmingxu00** [comment]
OU room, I got the name but forgot. I asked him if he changed his name after tour started, or changed anything drastic and he said no. I'm very slowly working on tour improvements, so I think I should look into this over the weekend?

**Comment by Zarel** [comment]
I believe logging out would do this.

**Comment by monsanto** [comment]
Not actionable
