### ISSUE TITLE
Pokémon List Glitches

### ISSUE THREAD

**Issue by Lord-Felidae** [smogon/pokemon-showdown#5950]
When I open the Pokémon list for the first time each time I visit the website, Mega Evolutions show the tiers of their base form, and they’re still in the correct part of each list.

I also can’t type in the shorthand for the tiers like OU, UU, CAP, etc
![F72237BF-CE58-4CC0-AF1A-6F0EFCDE7039](https://user-images.githubusercontent.com/19195628/68976121-f908c800-07ec-11ea-8602-558c74255cac.jpeg)
![C89A7046-19BC-4D8A-886D-00C8812FB8EE](https://user-images.githubusercontent.com/19195628/68976122-f908c800-07ec-11ea-93f6-bee567c4c3cd.jpeg)

(Sorry for poor image quality)

**Comment by Zarel** [comment]
Tier searching is only supported for the latest generation (Sword/Shield).

**Comment by Shiny-andKittens** [comment]
Is that then because you are in the middle of transitioning from Gen 7 to 8?

**Comment by Zarel** [comment]
Yeah.

**Comment by Shiny-andKittens** [comment]
K then, sorry for bothering you guys

**Comment by Zarel** [comment]
Well, the "RU" next to Diancie-Mega is a real bug.

**Comment by Shiny-andKittens** [comment]
It only happens for the first time each time I reload,

For example I open the menu one time, click on a Pokémon and then try to add another and it’s fine.

**Comment by Zarel** [comment]
I'm going to assume that this was fixed at some point.
