### ISSUE TITLE
Body Press is broken

### ISSUE THREAD

**Issue by Fikou** [smogon/pokemon-showdown#5975]
body press is supposed to use your defense stat as the attacking stat (at least i assume that from the move description)
but it uses your defense stat as the defending stat which makes it only good for glass cannons
https://replay.pokemonshowdown.com/gen8customgame-1011023106

**Comment by Shiny-andKittens** [comment]
I looked under the move’s code, it has a flag called `useSourceDefensive:true`.

This may be the root of the issue.

It looks like that could be used for confusion damage purposes and was applied to the move for some reason

**Comment by Shiny-andKittens** [comment]
Turns out, it is indeed the root of the issue.

I’ll try to make a fix for it.

**Comment by Zarel** [comment]
Oh, the move description was written so vaguely that I didn't realize that was what it was supposed to do. We had a confusing discussion about it on the Dev chatroom and it's not until now that I realized what the actual problem was.
