### ISSUE TITLE
Move Stuff Cheeks only raises Defense

### ISSUE THREAD

**Issue by jshenfield** [smogon/pokemon-showdown#6005]
Currently, Stuff Cheeks raises the Defense stat by two stages without consuming whichever berry the user holds

**Comment by jshenfield** [comment]
So actually, this didn't look like a difficult fix, so I had a try at writing the fix. Would I just submit a Pull Request after local testing/linting?

**Comment by Zarel** [comment]
Yeah, sure!

**Comment by KrisXV** [comment]
Fixed in #6023
