### ISSUE TITLE
Red card shouldn't work on dynamax pokemon [Medium priority]

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6007]
Minimum verifiable scenario:
Player A has a Red card Mimikyu, player B has  excadrill with earthquake and + 1 other pokemon. Excadrill dynamaxes on the first turn and uses earthquake, mimikyu survives the hit.

[match3-redcard.zip](https://github.com/smogon/pokemon-showdown/files/3862973/match3-redcard.zip)

What happens:
Redcard gets activated and Excadrill is forced to switch, losing the boosts, and dynamax form.

What should happen:
Redcard should get activated, the dynamax pokemon should not be switched, a message should be displayed stating that dynamax prevents red card from having an effect. 

Source from researcher:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-7#post-8283965

Notes:
I'm not 100% sure that the item will be used up, but I'm assuming that since it was activated, it will no longer activate in the future.

Edge cases:

Excadrill uses Max Guard to dynamax, then attacks, still gets phazed.
[match1-redcard.zip](https://github.com/smogon/pokemon-showdown/files/3862976/match1-redcard.zip)

Red card user is not mimikyu, still gets phazed.
[match2-redcard.zip](https://github.com/smogon/pokemon-showdown/files/3862974/match2-redcard.zip)

**Comment by TZubiri** [comment]
Dragon tail has the same problem.

Original replay: https://replay.pokemonshowdown.com/gen8unratedrandombattle-1012759985

User report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288061

Minimum verifiable scenario: https://replay.pokemonshowdown.com/gen8ou-1012788547

Edge case: Max guarding before getting dragon tailed, bug still present.. https://replay.pokemonshowdown.com/gen8ou-1012790127

**Comment by urkerab** [comment]
The Red Card shows "The move was blocked by the power of Dynamax!"? Lazy programming! Although I guess that makes it easier to implement in Showdown, since it just needs a new `-block` message or some such.
