### ISSUE TITLE
Choice scarf shouldn't have an effect during the turn a pokemon dynamaxes. [Medium priority]

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6008]
Minimum verifiable scenario:
Player A has a choice scarf Haxorus with dragon claw, Player B has a life orb Dragapult with dragon pulse. Player A dynamaxes and attacks, player B attacks as well.
Both pokemon have neutral speed natures and 0 speed evs.
https://replay.pokemonshowdown.com/gen8oubeta-1012442381

What happens:
Haxorus attacks first.

What should happen:
Dragapult should attack first.

Source from researcher:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8287541

Edge cases:
If Haxorus uses Protect while dynamaxing, and on the second turn uses the attacking move, then Dragapult will act first, which is the correct behaviour.
https://replay.pokemonshowdown.com/gen8oubeta-1012443471
If haxorus uses choice band, the item has no effect during any dynamax turn. This is the correct behaviour.
https://replay.pokemonshowdown.com/gen8oubeta-1012444670

Notes:
The fact that choice scarf effect works during the first turn is probably unintended and has something to do with the order in which who moves first is determined.
There have been changes between gen 7 and 8 regarding how speed works that might affect this issue, and even explain why the simulator implementation differed from cartridge.
It's ok to submit a quick patch for this issue, but later work needs to be done so that the core speed mechanics more closely match that of the game. Specifically speaking, that the order of moves not be determined at the start of a turn, rather that it change with speed changes mid-turn.
Sources:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8286116
https://twitter.com/i/web/status/1196444365750784005

**Comment by TZubiri** [comment]
Either the bug was not fixed, or there has been a regression.  :(

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288643

Confirmation:
https://replay.pokemonshowdown.com/gen8ou-1013464363
https://replay.pokemonshowdown.com/gen8ou-1013135817-pqfgrbz6u84ht1y8ewfuxab5f532v0qpw Turn 22

**Comment by Zarel** [comment]
Fixed properly in 65b17bc669e9b
