### ISSUE TITLE
Learnsets displayed on teambuilder should be the same as those used for server validation. [Medium priority]

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6012]
This encompasses a large amount of inaccuracies presented when selecting moves for pokemon, for example, teambuilder assumes the following incorrectly:

- Aegislash can learn toxic
- Pelipper can learn defog
- Gyarados can't learn power whip

Unless I am missing something, whatever data source validation is using (the one used server side when matchmaking, and the one used client side when clicking the "validate" button in teambuilder) could be used to generate the list of moves to present to the user. If the data source is the same, then I'm not sure what's causing these inaccuracies.

Original User report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8287549
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-70#post-8286360
Several comments on the OU chat.

**Comment by TZubiri** [comment]
Related: https://github.com/smogon/pokemon-showdown-client/issues/1399

Perhaps the client and server repos could be merged. A big selling point of using node js is to reuse client and server code.

**Comment by Zarel** [comment]
Fixed in #1403

**Comment by Zarel** [comment]
I mean, in smogon/pokemon-showdown-client#1403

**Comment by Zarel** [comment]
Client issue #1399 is entirely unrelated.

**Comment by Zarel** [comment]
Validators and move lists are necessarily separate. Obviously, the validation code handles egg move validation and event move validation; it's way too powerful/slow for just generating move lists.
