### ISSUE TITLE
Hover tooltips stopped displaying. [Low Priority]

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6019]
In the javascript console I get error messages like these :
`
TypeError: this.makeModifiedStatText is not a function
TypeError: pokemon.hpDisplay is not a function
`
The only tooltip that works is hovering over the pokemon when switching in.

Opening an incognito window fixes this bug, which makes me think that there's some version mismatch between some js files. stored in cache.

**Comment by Zarel** [comment]
Is this still happening? Reopen if so, and give the full stack trace from the JavaScript console.

**Comment by TZubiri** [comment]
Stack trace when hovering over opponent's pokemon:
```
showPokemonTooltip (module.js#492)
showTooltip (battle-tooltips.js#314)
showTooltipEvent (battle-tooltips.js#243)
dispatch (jquery-2.1.4.min.js#3)
handle (jquery-2.1.4.min.js#3)
```

State vars in showPokemonTooltip function show that `this` only has the members, battle, clickTooltipEvent,holdLockTooltipEvent and showTooltipEvent
`<this>: {…}
​​
battle: {…}
​​
clickTooltipEvent:BattleTooltips/this.clickTooltipEvent()
​​
holdLockTooltipEvent:BattleTooltips/this.holdLockTooltipEvent()
​​
showTooltipEvent:BattleTooltips/this.showTooltipEvent()
​​
<prototype>: {…}`

**Comment by monsanto** [comment]
Old client bug, if its still an issue would need someone to give instructions on how to reproduce.
