### ISSUE TITLE
Dynamaxing -gmax pokemon lose their ability.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6025]
Pokemon ending in -Gmax version, like Hatterene, will lose their ability when dyna/giga maxing.

Hatterene-gmax selected on teambuilder: https://replay.pokemonshowdown.com/gen8ou-1012939624
Regular Hatterene:https://replay.pokemonshowdown.com/gen8ou-1012944184

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288252

**Comment by Zarel** [comment]
This is probably a good reason not to treat it as a forme change, honestly.
