### ISSUE TITLE
Anything goes Gen 7 ladder no longer available .

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6028]
Not sure if this was intended, it's understandable that some tiers need to be removed for the new gen, perhaps this could be communicated through the news section. Is the decision based on usage statistics?

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288227

**Comment by Zarel** [comment]
@TheImmortal

**Comment by TheImmortal** [comment]
It has been re-added for now. However, it will be removed within the next month.

Read this for details on past gen ladders: https://www.smogon.com/forums/threads/changes-to-old-gens-ladders-a-public-vote.3621653/
