### ISSUE TITLE
Some pokemon (alolan formes) should't be available in gen 8.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6030]
Although it's hard to  [prove a negative](https://en.wikipedia.org/wiki/Burden_of_proof_(philosophy)#Proving_a_negative), a researcher has confirmed that he has never seen or heard of anyone seeing or catching an alolan forme pokemon. This includes Alolan pikachu, Raichu, vulpix, ninetales, diglet, dugtrio, meowth and persian.

Additionally, regular forme ponyta, rapidash and corsola don't appear to be catchable either.

I'd advise to get input from researchers on other candidates for removal before implementing the change. 

Sources:

Using regular corsola as an example: https://gamewith.net/pokemon-swordshield/article/show/13497 https://rankedboost.com/pokemon-sword-shield/corsola/

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288314

**Comment by KrisXV** [comment]
All of the unobtainable Kantonian formes of Galarian Pokemon are already marked as unreleased. However, the Alolan formes have been handled in #6034
