### ISSUE TITLE
In random battles some pokemons have no moves.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6036]
Pokemon known to be affected by this bug are meloetta, castform and minior, this can happen in challenge cup 1v1 and random battles.

Original user reports:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288035
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288601
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/page-75#post-8288432

**Comment by TZubiri** [comment]
Not fixed by https://github.com/smogon/pokemon-showdown/commit/1aa1cc3042ec4cee41fa48fa0432797287c93bf1

Not sure what dex challenge cup is supposed to use, but the replay posted also has a blastoise 

Original user report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8289070
Replay:
https://replay.pokemonshowdown.com/gen8challengecup1v1-1013491705

**Comment by whalemer** [comment]
That replay's still from before the format hotpatch, it hasn't been reported since. I ran a quick (10k tries) smoke test and couldn't replicate it, either.

**Comment by TZubiri** [comment]
I just noticed the timestamp in the replays, that's useful!

Closed
