### ISSUE TITLE
dynamax Weather ball should change type depending on weather.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6037]
When dynamaxing, weather ball should change to the type of the current weather. Currently it stays as normal (Max Strike) regardless of weather. In the game, the move displays as Max Strike regardless of weather, so no client code change is necessary.

Minimum verifiable example:

https://play.pokemonshowdown.com/battle-gen8ou-1013491289

Original report:

https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8288457

Research:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8284044

**Comment by TZubiri** [comment]
We don't have researcher confirmation regarding Nature power and secret power, but I assume the same changes should apply.

**Comment by ykabusalah** [comment]
Can I tackle this issue?

**Comment by TZubiri** [comment]
Thank you for your interest in contributing!

> Can I tackle this issue?
I see you have requested to solve more than one issue. In order to avoid blocking the resolution of more issues than necessary, I have assigned only one of them.

So this issue still remains unassigned.

**Comment by 420Blazeitt** [comment]
mine

**Comment by TZubiri** [comment]
Thanks for your interest in contributing!

I have assigned this issue to you. 

You can go ahead and start working on it, if you get stuck or have any technical questions, feel free to post them on [this](https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md) thread.

If you manage to fix the bug and are confident in your solution, please read this before requesting a pull.

Good luck!

**Comment by TZubiri** [comment]
I've taken a look at the code for this, I can think of two distinct ways to tackle it, out of curiosity, what's your plan?

**Comment by Zarel** [comment]
Note that this should also apply to other type-changing moves.

For instance, a Pixilate Normal move will become Max Starfall.

**Comment by 420Blazeitt** [comment]
> Note that this should also apply to other type-changing moves.
So, would this apply to Natural Gift and Hidden Power? How if it this would apply?

**Comment by Zarel** [comment]
@420Blazeitt Natural Gift and Hidden Power were Dexitted, but I would make them apply the same way.

**Comment by 420Blazeitt** [comment]
So some more stuff: https://www.smogon.com/forums/threads/national-dex-mechanics-thread.3656786/
This thread explicitly states that Judgment will always be normal type, so would that apply to all non natdex moves?

**Comment by Zarel** [comment]
@420Blazeitt That's just the thread describing the mechanics as they currently are implemented on PS, not as what they should be. Don't worry about it.

**Comment by TZubiri** [comment]
It seems that the scope of this issue has evolved to encompass other moves.

@Zarel Would it be possible for Mr. BlazeItt to implement a patch that just fixes weather ball? You could work on parallel on a solution that fixes the class of bugs.

If the incremental patch is finished first, we can implement it. If you later come up with a general solution, we can roll back the incremental patch(es) and implement the general solution.

This way BlazeIt (Any nicknames we can use?) could gain insight by actually seeing the solution you are describing, while still having collaborated with getting a feature earlier, and providing an out in case the general solution is a no-go, or you become drawn into a higher priority issue.

**Comment by 420Blazeitt** [comment]
> That's just the thread describing the mechanics as they currently are implemented on PS, not as what they should be. Don't worry about it.

ohh ok thanks for the assurance

**Comment by 420Blazeitt** [comment]
This issue is fixed in #6080

**Comment by Zarel** [comment]
@TZubiri honestly, I'm not too fond of half-measures. I'll allow them for super-high-priority problems, but thisi isn't one of them.

**Comment by Zarel** [comment]
Fixed in #6080
