### ISSUE TITLE
Species exception for toxtricity and toxtricity-low-key in doubles

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6038]
An approval from smogon tier makers might be appropiate here, but given that they have plus and minus abilities, it makes sense to treat them as minun and plusle and allow them in battle.

Original user report:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8289089

**Comment by TZubiri** [comment]
Definitely consult with smogon tiering authorities on this one, the abilities could still be used with other plus/minus pokemon even if species clause forbids their use in doubles.

**Comment by TheImmortal** [comment]
It definitely will not be allowed due to Species Clause.

**Comment by Zarel** [comment]
Species Clause has always been "no two Pokémon with the same Dex number" and there's no reason we'd ever change it for something as unimportant as this.
