### ISSUE TITLE
National Dex: Pokemon moveset validation should ignore nature restrictions in gen 8. 

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6040]
Apparently, there's a new item that can change the nature of pokemon, so if pokemon could be transferred to the new gen, the ability restriction would be lifted.

Original user report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8289167

**Comment by ykabusalah** [comment]
Can I tackle this issue too?

**Comment by subash955** [comment]
I'd like to give this one a shot, trying to get started with contributing.

**Comment by TZubiri** [comment]
Thanks for your interest in contributing!

> Can I tackle this issue too?
I have assigned you another issue you were interested in.


> I'd like to give this one a shot, trying to get started with contributing.
Thanks for your interest in contributing!

I have assigned this issue to you. You can go ahead and start working on it, if you get stuck or have any technical questions, feel free to post them on this thread.
If you manage to fix the bug and are confident in your solution, please read [this guide](https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md) before requesting a pull.

Good luck!
