### ISSUE TITLE
Utility Umbrella missing

### ISSUE THREAD

**Issue by RoccoDev** [smogon/pokemon-showdown#6061]
Pokemon Sword and Shield introduced a new held item, the Utility Umbrella, which negates weather effects to the holder.

https://www.serebii.net/itemdex/utilityumbrella.shtml

**Comment by RoccoDev** [comment]
The description is a bit misleading, since it doesn't protect you from let's say, Hail damage.
I need to run more research, I might fix this myself.

**Comment by HoeenCoder** [comment]
Were aware, we need to make some engine changes to get this to work. I can probably work on this soon (later today maybe).

**Comment by Zarel** [comment]
What does and doesn't this prevent, anyway?

**Comment by Zarel** [comment]
Fixed in #6120
