### ISSUE TITLE
Speed calculation under weather triggered abilities?

### ISSUE THREAD

**Issue by betairylia** [smogon/pokemon-showdown#6070]
Hi, I know gen8 is currently under test. here's probably a problem:

https://replay.pokemonshowdown.com/gen8battlestadiumdoubles-1016567180
Turn 4 (I am sunny side)

Not checked the in-game behavior though, so if I have expected something weird please forgive me...
( I will try to check that in the game later.

Vanilluxe: scarf (guessed), maximum speed should be 216 (144 * 1.5);
However the Leafeon has the ability Chlorophyll, with 252EV (neutral nature) on Spe, resulting 294 Spe stat (147 * 2):

Leafeon @ Choice Band  
Ability: Chlorophyll  
Level: 50  
EVs: 252 Atk / 4 SpD / 252 Spe  
Adamant Nature  
- Solar Blade  
- Leaf Blade  
- Double Kick  
- Quick Attack

In this turn leafeon chose the move Solar Blade. ( not sure if it was related to this specific move, bcz it works fine in other match
So the expected behavior should be leafeon uses its solar blade before the blizzard, if I understood this generation's speed calculation correctly (it was calculated dynamically)
Not sure where goes wrong, just want to discuss (perhaps my head goes wrong sry)

Or, is it just because the lack of notication when Quick Claw was triggered?
I think it will play an animation in-game...

Thanks!

**Comment by Zarel** [comment]
I'm surprised there wasn't already an issue about this. But yes, Speed is updated dynamically this gen, which has yet to be implemented.

**Comment by betairylia** [comment]
Thanks for your reply! It was not implemented yet?
Do you mean weather abailities or including weather etc. ? Sometimes it feels (honestly at most time) that it was already implemented while using prankster tailwind.

**Comment by HoeenCoder** [comment]
This was fixed in #6100
