### ISSUE TITLE
Shadow Tag Bug in Gen 8 Unrated Random Battle

### ISSUE THREAD

**Issue by samiurrahman98** [smogon/pokemon-showdown#6073]
See first two turns of replay: https://replay.pokemonshowdown.com/gen8unratedrandombattle-1016910036

Wobbuffet enters battle and Gardevoir traces Shadow Tag.
Expected: neither pokemon can switch out of battle
Actual: both pokemon switched out of battle

Neither pokemon is a ghost type.

**Comment by Zarel** [comment]
https://dex.pokemonshowdown.com/abilities/shadowtag

Shadow Tag has had an exception for other Shadow Tag users ever since Gen 4, because of the Gen 3 Wobuffet infinite game glitch.

Please research mechanics before filing issues in this tracker. I don't want to have to block you.
