### ISSUE TITLE
Metronome Battle allows max all EVs and illegal abilities

### ISSUE THREAD

**Issue by AffanIndo** [smogon/pokemon-showdown#6078]
![Capture](https://user-images.githubusercontent.com/18306510/69621183-2ff29f80-1071-11ea-9438-e890e25e7a3a.PNG)

Also it allows mega-sableye with choice scarf
Or 2 mega heracross with intrepid sword
Or blissey with imposter
Basically kinda like hackmons
The gameplay rn is kinda whack

Also there's some weird thing happened when you trying to dynamax when you have struggle.

**Comment by Zarel** [comment]
I'm pretty sure Metronome Battle was intentionally made to be like Hackmons. @TheImmortal?

**Comment by Zarel** [comment]
https://www.smogon.com/forums/threads/metronome-battles.3632075/

**Comment by Zarel** [comment]
@AffanIndo Please do not make bug reports without making sure they're actually bugs. I don't want to have to ban you.

**Comment by TheImmortal** [comment]
More like custom game even than hackmons.
