### ISSUE TITLE
In doubles, if the opponent is the last pokemon Dragon Darts should hit twice.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6086]
What happens: If the opponent's pokemon is the last pokemon in a doubles battle, Dragon darts only hits once.

What should happen: Dragon darts should hit the opponent twice.

Minimum verifiable Replay: Turn 3 -  https://play.pokemonshowdown.com/battle-gen8doublesou-1017319578

Original user report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291308

**Comment by Zarel** [comment]
This should be reasonably straightforward.

**Comment by Zarel** [comment]
Dragon Darts has smart targeting; this is related to #6085

The important situations where Dragon Darts will smart target (two darts at other foe):

- one foe fainted
- one foe protecting
- one foe Fairy-type

**Comment by Zarel** [comment]
Your replay link doesn't work. :[
