### ISSUE TITLE
Dynamax pokemon should take 5% of HP from Life Orb, not 10%.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6087]
What happens: A dynamaxed pokemon with life orb takes 10% of its doubled hp as recoil

What should happen: Dynamaxing pokemon should take 10% of its base (non dynamax) hp. If a calculation deals with percentage HP, [it should probably be based on non-dynamax hp.](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8283972)

 minimal replay: https://replay.pokemonshowdown.com/gen8ou-1017335276 

Original user report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291322

**Comment by Zarel** [comment]
This apparently also applies to Disguise, Life Orb, Leech Seed, etc, according to your post here:

- Dynamax HP loss is still wrong, but that should be fixed at the source.maxhp level so that it covers other cases such as life orb, leech seed, etc...

Can you find more research?

**Comment by Zarel** [comment]
Do you have a list of moves that work on max HP vs base max HP?

G-Max Finale is confirmed to work on max HP unlike Life Orb etc.

**Comment by TZubiri** [comment]
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8283972

G max moves might be the exception, however, this implementation detail would only make a difference when comparing two pokemons of different dynamax level.

**Comment by Zarel** [comment]
That's a post from an unbadged user extrapolating from two data points; I wouldn't trust it wholeheartedly.

In case it was unclear, Smogon researchers have this badge:

![image](https://user-images.githubusercontent.com/551184/69796896-b525b200-1233-11ea-8f46-0e8feaa804c2.png)

Although any badge is more trustworthy than no badge.

**Comment by Zarel** [comment]
I'd be willing to believe that most moves do work off base max HP, but I also expect there to be exceptions.
