### ISSUE TITLE
Mechanic differences relating to dynamax interaction with move restrictions.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6088]
There seems to be a difference in how dynamax interacts with move restricting effects such as:
Cursed body, disable, encore, out of pp. Probably taunt as well.

Original user reports:

[Choice lock + disable 1](https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291398)

>Was locked playing with Rotom-W, choice locked into hydro pump, which got disabled by Corsola's ability. The only option left was struggle as it should be, but clicking Dynamaxing led to only the water type Dynamax move being displayed, there wasn't any other moves to click.

[Choice lock + disable 2 replay, Turn 5](https://replay.pokemonshowdown.com/gen8randombattle-1016745310)

> : so I'm choice specs locked
>  and because of disable, I'm locked into struggle
>  dynamaxing is supposed to remove choice locking
>  but for some reason, when I go to dynamax, it only allows me to use the max move of the move I'm locked into
>  actually... it's locking me into a dark max move which is odd

[Bonus edge case, single move metronome, turn 3:](https://replay.pokemonshowdown.com/gen8metronomebattle-1015311711)☆HGgamer: i'm struggeling because of disable

> P1: and i want to dynamax
> P2: yep, struggle is broken
> P2: happened the same to me last match
> P1: so the game doesn't know what to do

**Comment by SadisticMystic** [comment]
If clicking the fight button in game would force a Struggle due to lack of selectable moves, the correct behavior is that the Dynamax button does not appear at all, and you do not get an opportunity to break the disabling effect by using that. Same as how Z-moves worked.
