### ISSUE TITLE
Dynamaxing should drop existing substitutes.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6089]
What happens currently: If a pokemon uses substitute, and later dynamaxes, the substitute is still in place, and the dynamax pokemon takes no damage the next turn.

What should happen: The substitute should be removed, it should not come back after dynamax ends.

Original user reports:
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291171
https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291115

Ingame confirmation:
https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8287292

**Comment by Zarel** [comment]
The replay in the thread predates the Steel Beam fix, so I can't use it. :(

**Comment by TZubiri** [comment]
I do test them before posting, I'll start adding the link to the replays as well. https://play.pokemonshowdown.com/battle-gen8ou-1017556143
