### ISSUE TITLE
VGC 2017 format not allowing Heatran.

### ISSUE THREAD

**Issue by TZubiri** [smogon/pokemon-showdown#6095]
The error message reads " - Heatran is not in the Alola Pokédex.".

Original user report: https://www.smogon.com/forums/threads/bug-reports-v3-read-original-post-before-posting.3634749/post-8291904

**Comment by Zarel** [comment]
Heatran is not supposed to be in the Alola Pokédex. Please do not report bugs without verifying them first. I don't want to have to block you.
