### ISSUE TITLE
Unburden ability and Electric Seed

### ISSUE THREAD

**Issue by Eelpi** [smogon/pokemon-showdown#6125]
Electric seed is consumed but speed is not raised

**Comment by Zarel** [comment]
This repository is not to be used for unconfirmed bug reports. To prevent further abuse, I've blocked you.

For future reference, a confirmed bug report requires a PS replay link, as well as a YouTube video of the correct mechanic.

Alternatively, try https://psim.us/bugs, which is less strict about bug reports.

**Comment by Zarel** [comment]
As for your specific problem, the answer is that when using Unburden, Speed is raised secretly, with no message shown, which testing on the Switch would have told you.
