### ISSUE TITLE
Endeavour vs. Dynamax

### ISSUE THREAD

**Issue by betairylia** [smogon/pokemon-showdown#6131]
It seems like only the "original" part of HP rather than full HP was considered while dynamax pokemons being targeted by endeavor (in cartridge).
However in showdown, full HP was considered.

e.g. 1/100HP endeavor -> 225/300 dynamax (original HP 150) = 76/300 dynamax.
In showdown, it will become 1/300 dynamax.
( Seems like damage was firstly taken by boosted HP, so 1hp endeavor will still take 1x original HP from a non-healthy dynamax pokemon.

Only tested in battle tower, my 1HP sash whimiscott used endeavor to my max charizard (290/306 or so) and its HP bar turns yellow.

Currently in showdown endeavor is insanely op as it can take the entire HP bar from any max pokemon, but no one was using that tho lol

**Comment by Zarel** [comment]
I don't understand what this means.

It looks like 1/100 Endeavor is doing 149 damage to a 225/300 Dynamax Pokémon? Why? What's the formula?

**Comment by betairylia** [comment]
> I don't understand what this means.
> 
> It looks like 1/100 Endeavor is doing 149 damage to a 225/300 Dynamax Pokémon? Why? What's the formula?

300 hp dynamax = 150 hp original, so its like endeavor takes this 150 to 1 so 149 dmg was done.
Boosted HP was consumed at first (not confirmed) so 300 hp dynamax take 149 dmg from 1hp endeavor if current hp >= 150.

Still needs to be checked in game tho, probably I could send you some videos

**Comment by Zarel** [comment]
But you said 225/300 HP Dynamax. Endeavor works on HP, not on max HP. Where are you getting 150 HP from?

**Comment by Zarel** [comment]
I've asked testers and they've been getting confusing results that no one really knows how to make sense of.

**Comment by betairylia** [comment]
> But you said 225/300 HP Dynamax. Endeavor works on HP, not on max HP. Where are you getting 150 HP from?

I think the rule behind this might be:
those kind of damage (based on HP) was calculated first using max-poke's current HP, but then upper bounded by the damage to original form.

e.g. 225/300 dynamax - original form was considered as 150/150 (as current HP cannot be larger than maxHP)
- endeavor vs. 225/300 -> 1/300 -> 224 dmg
- endeavor vs. 150/150 -> 1/150 -> 149 dmg
so the final dmg done was 149 dmg (min(224,149)).

That's what I have seen so far, it should be good if you can share the results from testers.

**Comment by betairylia** [comment]
So like, all dmg was calculated based on original form, while if current dynamax HP > original maxHP it was considered as full-health. Then the dmg was applied to the dynamax form;
so 225/300 will be considered as 150/150 and 149 dmg was taken then applied to dynamax, which yields 76/300

**Comment by betairylia** [comment]
> So like, all dmg was calculated based on original form, while if current dynamax HP > original maxHP it was considered as full-health. Then the dmg was applied to the dynamax form;
> so 225/300 will be considered as 150/150 and 149 dmg was taken then applied to dynamax, which yields 76/300

Just a hypothesis, I m not sure ...

**Comment by Zarel** [comment]
I had my researchers test this, and you're wrong.

It should be

 1/100HP endeavor -> 225/300 dynamax (original HP 150) = **113**/300 dynamax

**Comment by betairylia** [comment]
> I had my researchers test this, and you're wrong.
> 
> It should be
> 
> 1/100HP endeavor -> 225/300 dynamax (original HP 150) = **113**/300 dynamax
> 
> not 76

I see, thanks.
seems like the dmg was halved?

**Comment by betairylia** [comment]
BTW how could you reproduce this particular setting in game so quick (like 100 and 150 max HPs)

**Comment by betairylia** [comment]
Sorry for the confusion ...

**Comment by Zarel** [comment]
It wasn't quick, it's been three hours since I asked my researchers to start testing Endeavor.

**Comment by architdate** [comment]
> I see, thanks.
> seems like the dmg was halved?

Not really. If you wanna really look at the workings behind it, refer to [this post](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/page-29#post-8301556) on the mechanics thread

A simple pythonic implementation of the logic is as follows:
```py
import math
def calc_hp(endeavor_hp, dynamax_hp, dynamax_level):
    base_hp = math.ceil(dynamax_hp/dynamax_level)
    damage = base_hp - endeavor_hp
    return dynamax_hp - damage
```

**Comment by betairylia** [comment]
> It wasn't quick, it's been three hours since I asked my researchers to start testing Endeavor.

Thanks for your effort ... Sorry for my silly description. It makes sense to me now
