### ISSUE TITLE
Desktop client crashes when hiding right side panel

### ISSUE THREAD

**Issue by jordanhui19** [smogon/pokemon-showdown#6153]
The client crashes when hide is clicked after everything is loaded. It works if its clicked before the ads are loaded though.

**Comment by whalemer** [comment]
I'm pretty sure this would be fixed by rebuilding the desktop client with a newer nwjs, cough, cough, @Zarel, cough.

**Comment by Zarel** [comment]
pre said he might handle it and then didn't. I just can't without a Windows install and a lot of messing around. :/

**Comment by Zarel** [comment]
Fixed in smogon/pokemon-showdown-client#1459
