### ISSUE TITLE
Speed Swap Bug

### ISSUE THREAD

**Issue by bobinchese** [smogon/pokemon-showdown#6170]
Not sure exactly what the bug is, but it looks like speed swap only applies for 1 turn where it should apply until the pokemon switches out. Notice how the snorlax moves first on turn 2, but is then slower than the arcanine (and later a weezing) on following turns.

![image](https://user-images.githubusercontent.com/12100332/70465813-c66e8a00-1a8f-11ea-8ef9-e51347633973.png)

**Comment by bobinchese** [comment]
After playing more games, it seems like the speed boost is lost when the affected pokemon dynamaxes.

**Comment by Zarel** [comment]
Do you have a replay?

**Comment by Zarel** [comment]
I'll reopen if you provide a replay and I get confirmation that this is a real bug.
