### ISSUE TITLE
Berries should be consumed by Teatime

### ISSUE THREAD

**Issue by hangy233** [smogon/pokemon-showdown#6210]
After using Teatime, Berries should be consumed instead of being available to immediately be used again.

**Comment by Zarel** [comment]
???

I don't understand your claim.

In any case, if you want to report a mechanics bug, we require a PS replay showing the wrong mechanic, and a YouTube video of the correct mechanic on the Switch.

**Comment by architdate** [comment]
Berries being reused after teatime seems to be the correct working according to [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Teatime_(move))

Teatime mechanic is as follows:
- When teatime is used, berries on the field are activated but NOT used up. Ergo standard activation still applies
- Once a pokemon consumes its berry normally, teatime will fail.

To check: Harvest mechanics with teatime after berry consumption and repeated teatime spam on something like a starf berry!

**Comment by hangy233** [comment]
@architdate @Zarel  Pretty sure that's not how teatime works and bulbapedia is not always correct.
Here's a [youtube video](https://youtu.be/x6kVFGOb0Jk) (Please pardon the Chinese.  But you can tell from the animation.)
[PS replay](https://replay.pokemonshowdown.com/gen81v1-1034606040)

Please reopen this issue and sorry for not including the video and the replay in the first post.

**Comment by Zarel** [comment]
I can read Chinese so it's not a problem. That video certainly shows Teatime failing when used repeatedly, so it looks like our understanding of it is incomplete.

**Comment by Zarel** [comment]
![image](https://user-images.githubusercontent.com/551184/71385420-e1620200-262a-11ea-8ed5-2390733db789.png)

**Comment by Zarel** [comment]
Anubis's source for Teatime bypassing Unnerve:

https://imgur.com/a/VXjHvrs
