### ISSUE TITLE
[Feature Request] API to build teams and play games against oneself

### ISSUE THREAD

**Issue by Atrus619** [smogon/pokemon-showdown#6267]
## The Ask
The title essentially says it all, but I'm interested in an API that would allow me to interact with a pokemon showdown server and build teams / play games against myself using an external program such as Python. I have limited experience with NodeJS and PHP, so I figured I would ask if something already exists / could be built by the development team before I attempt to implement it myself. 

Worst case, it would be great if someone more experienced than myself could point me in the right direction towards accomplishing this goal! I am an avid learner, and don't mind doing the work myself.

## Use Case / Context
I am a deep reinforcement learning researcher, and would like to experiment with various algorithms to train an agent to play competitive pokemon at superhuman levels. Having access to an API to utilize pokemon showdown would be invaluable. I am a huge fan of pokemon showdown, having played it for many years (and played the video games since gen 1 of course!) and think it is the perfect environment for this research.

Let me know if you have questions, comments, or concerns. I really appreciate the help!

**Comment by Slayer95** [comment]
Dupe of #4841

**Comment by Atrus619** [comment]
Apologies, I did my due diligence of looking through prior issues to see if it was resolved already, but evidently missed this one.

Thank you - this should work perfectly!
