### ISSUE TITLE
Body slam appears to be able to paralyze normals in gen 1

### ISSUE THREAD

**Issue by spergmoment** [smogon/pokemon-showdown#6271]
ICYDK, it was discovered recently that body slam didn't paralyze normal types in gen 1 (God damn, as if they weren't already an incredibly broken type)

It appears it is possible in PS Gen 1 to paralyze normals. Should probably be fixed. Should be just a tag in the body slam text in moves.js
Assuming you just need to add this:
```
    if((target.type!=="normal"&&this.gen===1)||this.gen!==1) {

    		secondary: {

			chance: 30,

			status: 'par'

		}

        }
```

**Comment by tmagicturtle** [comment]
This is handled in scripts.js, beginning on line 608.

**Comment by monsanto** [comment]
PS implemented support for this when it was discovered. If you think you've found a bug please provide a replay exhibiting the behavior. Thanks!

**Comment by spergmoment** [comment]
In my experience, it was able to, probably just a dumbass lmao
