### ISSUE TITLE
2 Ability Clause doesn't work

### ISSUE THREAD

**Issue by Gamebuster19901** [smogon/pokemon-showdown#6305]
```
2 Ability Clause: Limit two of each ability
```

The 2 Ability Clause doesn't restrict to two of the same ability.

See
https://replay.pokemonshowdown.com/gen7balancedhackmons-1051241350

**Comment by KrisXV** [comment]
He has one Steelix with Comatose, and one Shuckle with Comatose. That's two Pokemon.

**Comment by Gamebuster19901** [comment]
Is it a client bug then? Why does it show 1 Shuckle and 2 Steelix with Comatose?

**Comment by Gamebuster19901** [comment]
You can see in this video here that it appears that there are 3 mons with comatose.

https://www.youtube.com/watch?v=6BtgDg5Rhdc&feature=youtu.be

**Comment by Zarel** [comment]
It's not a client bug, it's just what happens when your opponent has multiple identical pokemon. You, the human, can't tell them apart, so if the client could, the client would be leaking information that you're not supposed to know.

**Comment by Gamebuster19901** [comment]
I see, thanks.
