### ISSUE TITLE
Some Server Files are Exposed to Public Browsing (Web Vulnerability)

### ISSUE THREAD

**Issue by Zyresus** [smogon/pokemon-showdown#6311]
I will not go into full details on how to replicate this, as this is a public post, however to put it in simple context, some files (IE: config.js) are accessible via the root Showdown domain, following a certain format, which is easily accessible. 

This contains actual PS main custom code, and really shouldn't be publicly exposed.

If screenshots, or guidance to replicate is needed, please let me know via discord. 
Madilyn#1156

**Comment by monsanto** [comment]
config.js is supposed to be world-readable.

Please stop bothering our staff.

**Comment by Zarel** [comment]
https://play.pokemonshowdown.com/config/config.js

I assume you're talking about this one, in which case, yes, these are required by the client to run PS, of course it's public.
