### ISSUE TITLE
Move secondaries should run before the AfterDamage event

### ISSUE THREAD

**Issue by TheImmortal** [smogon/pokemon-showdown#6346]
Currently: the event triggers before secondaries (https://replay.pokemonshowdown.com/gen8customgame-1058947435)

What should happen: move secondaries should occur first (https://twitter.com/Sibuna_Switch/status/1225472059393769472)

It's not just this one ability but all abilities that currently use ``onAfterDamage``.

**Comment by Zarel** [comment]
It should be called `AfterMove` rather than `AfterDamage`, then.

**Comment by Zarel** [comment]
Hm, presumably it procs every hit of a multihit move.

Also presumably it's still before secondaries in previous games?

If not, I would probably call it `HitWithDamage`. Would it go before or after `Hit`?

**Comment by TheImmortal** [comment]
Yes, it procs after every hit.

No, it’s the same in previous gens; move secondaries run before the ability activates. I guess no one noticed until now.

**Comment by Zarel** [comment]
I'd call it `HitWithDamage` probably.

**Comment by Zarel** [comment]
Does it also happen to items? I see a lot of items with `AfterDamage` listeners.

**Comment by Zarel** [comment]
It sounds like every Ability is incorrectly using `AfterDamage`. Are they listening to damage from sources other than moves? Like poison damage, or Struggle recoil?

**Comment by Zarel** [comment]
Ugh, literally every `AfterDamage` listener contains a check that the effect was a move.

We've been using the wrong listener this entire time... :/ I'm going to need to rewrite literally every ability.

**Comment by Zarel** [comment]
Okay, Emergency Exit apparently happens after residual damage, too.

**Comment by Zarel** [comment]
How's that one timed?

**Comment by Zarel** [comment]
Also Wimp Out is apparently the same.

**Comment by Zarel** [comment]
https://github.com/smogon/pokemon-showdown/commit/edc2b8f98a08477c858b8aa8ef47e7115674d63f

@Marty-D This is just everything's damage ordering, not just Rowap/Jaboca in Gen 4, right? This isn't a Gen 4 specific mechanic, is it?

**Comment by Zarel** [comment]
If I move Rocky Helmet after secondaries, that means that I need to move Knock Off after secondaries too, right?

**Comment by TheImmortal** [comment]
Yes, items should work the same way. In-game Rocky Helmet activates after Iron Barbs even.

I don't know about Knock Off.

**Comment by TheImmortal** [comment]
Emergency Exit is different. It activates after all the hits of a multi-hit move.
