### ISSUE TITLE
[Gen 3] Clicking Baton Pass but not choosing a Pokemon doesn't count down the timer

### ISSUE THREAD

**Issue by plusfuture** [smogon/pokemon-showdown#6381]
As title. On ladder, with timer ON, if Baton Pass is chosen but the Pokemon is not, the timer does not count down. In fact, the timer seems to stop completely, meaning that even if the opponent disconnects the match will never end.

### Reproducibility
This will happen 100% of the time in a Gen3 game. I don't have a replay since the game doesn't end, but [here's a screenshot (imgur)](https://imgur.com/a/9rPQBtt)

**Comment by Zarel** [comment]
You can save a replay for a game that doesn't end with `/savereplay`.

**Comment by AlejandroRdzLpz** [comment]
This was already fixed or never happened as of today, Dec. 25, 2020.
https://replay.pokemonshowdown.com/gen3ou-1250316166
it clearly shows that after usin Baton pass, the timer counts down to 120 seconds left.

**Comment by Zarel** [comment]
Thanks for the update!
