### ISSUE TITLE
Gen 8 IV Legality Issues

### ISSUE THREAD

**Issue by Lusamine** [smogon/pokemon-showdown#6383]
Validator currently allows multiple Pokemon that should be illegal due to IV restrictions.

**EDIT**: With Max Soup out, G-Max Pokemon shouldn't have any more IV restrictions. 

------

Pokemon Go Transfers convert IVs in an interesting way.  Pokemon Go has 3 IVs for Attack, Defense, and HP that each range from 0-15.  The conversion in LGPE makes it so that:
Att = SpA = 2*Attack_Go + 1
Def = SpD = 2 * Def_Go + 1
HP = 2 * HP_Go + 1
Spe ranges from 0 to 31 randomly.
https://twitter.com/Kaphotics/status/1062863606188990464
This means that only odd IVs are allowed for everything except Speed, which can be any IV, and Att = SpA, Def = SpD if they aren't hyper trained.

The most obvious Pokemon affected is Meltan/Melmetal since they must be transferred from Pokemon Go to LGPE and then to Home.  This set should be illegal for the above reasons:
```
Melmetal  
Ability: Iron Fist  
EVs: 1 HP  
Brave Nature  
IVs: 0 SpA / 0 Spe  
- Double Iron Bash
```

Another affected Pokemon is Pressure Mewtwo with Teleport (LGPE TM), but this is rather complicated.  LGPE Mewtwo has 3 IVs guaranteed, but PoGo Mewtwo is normally obtained at a minimum of 10/10/10 and can then be traded between Good Friends to reach a minimum IV of 1/1/1 in PoGo.  This translates to a 3/3/3/3/3/0 minimum in Gen 8.  Mewtwo is also required to be a minimum level of 15 if it comes from Pokemon Go.
This should be legal in Gen 8:
```
Mewtwo  
Ability: Pressure  
IVs: 3 HP / 3 Atk / 3 Def / 3 SpA / 3 SpD / 0 Spe  
- Teleport
```

This should be illegal:
```
Mewtwo  
Ability: Pressure  
IVs: 1 HP / 1 Atk / 1 Def / 1 SpA / 1 SpD / 0 Spe  
- Teleport
```

Currently, I don't believe any other Pokemon Go Pokemon with boosted IVs that could be retraded to 1/1/1 are transferrable to SwSh, but if they were, the IV threshold would apply to other legendaries, Research Task-only Pokemon, and PoGo egg-only Pokemon as well.

**Comment by Lusamine** [comment]
Updated this for March promo den events which allow 3 IV G-Max Machamp and G-Max Gengar.

**Comment by Lusamine** [comment]
Updated for April promo den events which allow 3 IV G-Max Duraludon, G-Max Charizard, G-Max Garbodor, and G-Max Copperajah.  This also simplifies the G-Max Charizard check since 3 IV is no longer restricted to the shiny-locked gift Charmander.

**Comment by Lusamine** [comment]
Updated for G-Max Pikachu raids which allow 1 IV, shiny, HA, and Volt Tackle.

**Comment by Lusamine** [comment]
Updated for G-Max Eevee raids which allow 1 IV, shiny, HA.

**Comment by Lusamine** [comment]
Updated for G-Max Meowth raids which allow 1 IV, shiny, HA.

**Comment by Lusamine** [comment]
New info indicates we'll be able to add G-Max factor to mons that didn't have it, which renders most of this post obsolete once DLC1 comes out.

**Comment by Lusamine** [comment]
Updated the initial post for G-Max IVs now that we have Max Soup.  PoGo specific IVs are still a thing and we will have to keep an eye on G-Max Melmetal when it is released.

**Comment by DaWoblefet** [comment]
Closing with Anubis's approval now that GO legality stuff has landed.
