### ISSUE TITLE
Clicking cancel move and then re-selecting a move quickly enough breaks the game

### ISSUE THREAD

**Issue by plusfuture** [smogon/pokemon-showdown#6384]
https://play.pokemonshowdown.com/battle-gen3ou-1067515878

Basically, I cancelled then clicked another move quickly. I got the following message:
[Invalid choice] Sorry, too late to cancel; the next turn has already started

But then when I try to make a move:
[Invalid choice] Sorry, too late to make a different move; the next turn has already started

There's no way to end the game, and you can't even offer tie until turn 100.

**Comment by Zarel** [comment]
No, this is unrelated; it just so happened that the sim crashed when you did this.
