### ISSUE TITLE
Emergency Exit should activate for in-direct damage

### ISSUE THREAD

**Issue by TheImmortal** [smogon/pokemon-showdown#6424]
On PS: Life Orb, Weather, Poison do not trigger Emergency Exit
https://replay.pokemonshowdown.com/gen8ou-1071497552 (turn 16)
https://replay.pokemonshowdown.com/gen8ou-1067294574 (turn 17)

In-game: Life Orb, Weather, Poison do trigger Emergency Exit
https://streamable.com/i5kza
https://streamable.com/1qflz
https://streamable.com/3a8ky

**Comment by TheImmortal** [comment]
Bonus bug: Photon Geyser breaks Emergency Exit
https://replay.pokemonshowdown.com/gen7ru-1073961965

**Comment by Zarel** [comment]
I was _explicitly_ told that weather does not trigger Emergency Exit, and I would not have used this architecture if it did.

**Comment by Marty-D** [comment]
Who told you that? I mentioned the description on Smogon/PS has all the exceptions listed for you. 
"This effect applies to both direct and indirect damage, except Curse and Substitute on use, Belly Drum, Pain Split, and confusion damage."

Notably, it's the same exclusion list as Magic Guard, except for Struggle recoil which *does* activate Emergency Exit/Wimp Out.

**Comment by Zarel** [comment]
...apparently someone who got it from Bulbapedia. I remember repeatedly asking for a list, though, and I don't remember getting it. But I'm usually juggling six tasks at once and can easily miss things if you don't @ me.

**Comment by Marty-D** [comment]
That's fair, but reading the description on your own site should always be your first resort! If it's not detailed enough and you need to ask questions after, then it's probably worth adding some clarification to the description anyway.

**Comment by Zarel** [comment]
I was used to the descriptions being incredibly vague for Gen 8 mechanics, and I forgot EE was Gen 7.

**Comment by Zarel** [comment]
"This move and its effects ignore the Abilities of other Pokemon."

Wait, isn't Photon Geyser _supposed_ to break Emergency Exit?

**Comment by TheImmortal** [comment]
> "This move and its effects ignore the Abilities of other Pokemon."
> 
> Wait, isn't Photon Geyser _supposed_ to break Emergency Exit?

Mold Breaker does not, so Photon Geyser shouldn't either.

**Comment by Zarel** [comment]
Well, I isolated Photon Geyser in a test, and it doesn't suppress Emergency Exit. There's probably something else going on in that replay.

**Comment by TheImmortal** [comment]
Something to do with U-turn, maybe.

**Comment by Zarel** [comment]
Ah, that one turned out to be a really subtle bug. Fixed here: 38e4af504cae4e
