### ISSUE TITLE
Sim-protocol does not support dynamax moves + documentation missing dynamaxing

### ISSUE THREAD

**Issue by jzyrobert** [smogon/pokemon-showdown#6425]
Hi,

The simulator protocol does not support dynamax move ids when the active pokemon is dynamaxed.
Rather, you have to use the regular move name or index (e.g. 1-4).

Example:
- A dynamaxed pokemon has the 4th move `substitute` replaced with `Max guard`
- `/choose move substitute` or `/choose move 4` works
- `/choose move Max Guard`, `/choose move maxguard` do not work

Additionally, the documentation does not mention that `/choose move [id/index] dynamax` is the protocol for dynamaxing and using a certain move.

I'm rather busy at the moment, but if someone could point me towards where in the point this logic lies, I could have a go at submitting a PR soon.

**Comment by Zarel** [comment]
https://github.com/smogon/pokemon-showdown/blob/505836e27ec4cf39d9c3b9147761097aa710a8e2/sim/side.ts#L360-L373

I would actually really appreciate this.

Also if you try `/move maxguard` with an undynamaxed Pokémon, if it would auto-Dynamax, that would be even cooler.

**Comment by jzyrobert** [comment]
Does [this](https://github.com/jzyrobert/pokemon-showdown/commit/3fc0780d6c18942cd455effb80ed1d9bc1e1e9c5) look right?

I've tested it manually and it works as it should, could also add some proper tests for it.

**Comment by Zarel** [comment]
Looks good. I have suggestions but they're easier to do directly on the PR.

**Comment by Zarel** [comment]
(My thoughts are mainly: 1. this loop can be skipped by testing if `targetType` is truthy at this point, 2. if there are multiple max moves, the one with the higher base power should be selected, 3. if this could also be implemented for Z moves, that would be amazing.)

**Comment by Zarel** [comment]
Actually, probably #1 most important because GitHub's suggestion feature can't cover it: `getMoveRequestMoves()`'s return value should be saved from line 347. It's a pretty intense function that shouldn't be called repeatedly.

**Comment by Zarel** [comment]
I haven't heard back from you in two weeks, so I guess I'm fixing this myself.
