### ISSUE TITLE
Sucker punch in doubles

### ISSUE THREAD

**Issue by derrkater** [smogon/pokemon-showdown#6534]
As per serebii, sucker punch in 8th edition should fail when targeting an pokemon which uses an offensive move but not against sucker puncher.

**Comment by Lusamine** [comment]
Works fine here: https://twitter.com/Sibuna_Switch/status/1247395952257683457
Is there some other scenario where it's supposed to fail?

**Comment by derrkater** [comment]
Serebii says: Sucker Punch in Double Battles now only activates if the target was going to attack the user.

I guess serebii is wrong - my bad for not checking it ;) 

It would be good to run a test where the enemy pokemon is targeted by sucker and runs a damaging move against non-sucker puncher. Maybe pokemon from opposite sides are treated differently by this mechanic?

**Comment by Marty-D** [comment]
That's just a poor understanding of this mechanic: https://www.smogon.com/forums/posts/8312370/
It was also patched out of Sword and Shield since then.
