### ISSUE TITLE
Underscore management in player identifier

### ISSUE THREAD

**Issue by hsahovic** [smogon/pokemon-showdown#6567]
Hi!

How are underscores managed in player identifiers / usernames?

I can log in with an underscore in my username, but underscores are suppressed in some messages received from the showdown server.

In particular, I can do something like this:

`> |/trn b_username,0,...`

And receive this response:

`< |updateuser| b_username|...`

But when I do:

`> |/challenge b_username, gen8randombattle`

I receive:

`< |updatechallenges|{"challengesFrom":{},"challengeTo":{"to":"busername","format":"gen7randombattle"}}`

Is this the expected behavior, and if it is, why is it happening?

**Comment by Zarel** [comment]
PS has "username", which is the full username, and "userid", which is the username passed through the `toID` normalization function (which converts it to lowercase and removes everything except letters and numbers).

A lot of messages from the server use `userid` rather than `username`.

**Comment by hsahovic** [comment]
Thanks, that makes sense!
