### ISSUE TITLE
need some help navigating the code base

### ISSUE THREAD

**Issue by evanthebouncy** [smogon/pokemon-showdown#6586]
hi, we're looking to build an AI around the pokemon-showdown framework. I need someone to talk to to go over which piece of code does what and what needs to be looked at, as it will save me a huge amount of time.

I am not sure where is the best place to look, but it would be nice to know whom I should ask this. I looked over the chat-room under /dev but I cannot ask questions there, 

    Because moderated chat is set, your account must be at least one week old and you must have won at least one ladder game to speak in this room.

hence I'm posting here and hopefully there is a response. is there a point of contact that may eventually lead me (through some grapevine of deferrals) to the right person to talk to? let me know in reply or email me yewenpu@mit.edu

thanks in advance.

**Comment by Zarel** [comment]
Hi! The Development Discord is currently:

https://spo.ink/dev

Alternatively, tell me your PS account and I'll autoconfirm it.
