### ISSUE TITLE
super staff bros brawl! (Xatu and porygon have issues).

### ISSUE THREAD

**Issue by pooping-duck** [smogon/pokemon-showdown#6663]
in the super smash bros brawl tier, I just wanted to inform you that porygon gets his level cap at 105. Also Xatu can't use his move glitzer popping, it will always result in the move being called  "!" and a miss. Other than that i just wanted to thank everyone who works on ps, it really is an amazing website. :)

Also my first post here and i don't know if i'm doing this right, if not please inform me so that i can better myself. thank you.

**Comment by Zarel** [comment]
Do you have a replay? As far as I'm aware, this was fixed a while ago.

**Comment by pooping-duck** [comment]
> Do you have a replay? As far as I'm aware, this was fixed a while ago.

file:///C:/Users/WIN10/Downloads/Gen7SuperStaffBrosBrawl-2020-05-08-guest3293010-poopingduck.html

and 

file:///C:/Users/WIN10/Downloads/Gen7SuperStaffBrosBrawl-2020-05-08-poopingduck-guest3293010.html

**Comment by Zarel** [comment]
You need to click the "Upload replay" button. I can't do anything with files on your computer.

**Comment by pooping-duck** [comment]
> You need to click the "Upload replay" button. I can't do anything with files on your computer.

Very sorry about that, as you can tell I have limited knowlege when it comes to computers... haha anyway, here are the replays.

https://replay.pokemonshowdown.com/gen7superstaffbrosbrawl-1111032650

https://replay.pokemonshowdown.com/gen7superstaffbrosbrawl-1111033499

**Comment by Zarel** [comment]
Looks like server hasn't been hotpatched in three days. Glitzer Popping should be fixed now.
