### ISSUE TITLE
Flag to disable all outgoing connections

### ISSUE THREAD

**Issue by Slayer95** [smogon/pokemon-showdown#6691]
Over the years I've privately reported this issue and met zero interest on it, so I'm just overtly opening this as an issue now.

User-initiated commands which cause the server to contact third-party sites (``/showimage``, ``*-otd``, ``/yugioh``, etc) will [nullify all the protection that CloudFlare and other reverse proxies normally grant to PS servers](https://community.cloudflare.com/t/outgoing-requests/25212), so there ought to be a simple way, enabled by default, to:

* Disable any and all of these commands.
* Disable outgoing connections - note that, for completeness, this applies to ``login-server.ts`` as well.

**Comment by Zarel** [comment]
I don't remember this being reported to me ever, but it's possible I forgot. Anyway, yes, I'd support a flag for this.

Honestly, we should write our own HTTP request library and put it in `lib/`, which would support being disabled (like FS does).

**Comment by mia-pi-git** [comment]
should be noted, WIP in #6744
