### ISSUE TITLE
Flag to protect users from connecting to 3rd parties from embedded HTML/CSS

### ISSUE THREAD

**Issue by Slayer95** [smogon/pokemon-showdown#6692]
(#6691 is about protecting the PS server, this one actually affects users)

Arbitrary image URLs allow the site owner to record IP addresses of visitors.
Trivial execution for ROs.

This can be implemented client-side, but a server-side solution with proper HTML parsing and sanitizing with Caja has always been my preferred alternative (sadly rejected from step 0 in #2572).

**Comment by Zarel** [comment]
PS could proxy images or whitelist image hosts if we really cared, but in general we consider anyone who has HTML permissions sufficiently trustworthy not to do things like that (and IP addresses are difficult, anyway). I don't think this hole is worth plugging. Just demote anyone who actually tries to do this.

**Comment by Zarel** [comment]
To be clear for anyone watching at home: We already use Caja sanitization client-side, so there's no XSS vuln or anything like that.
