### ISSUE TITLE
Showdown zooming out on mobile

### ISSUE THREAD

**Issue by mattthzu** [smogon/pokemon-showdown#6737]
![Screenshot_20200524-212043](https://user-images.githubusercontent.com/65861475/82757799-35505d00-9dfc-11ea-90ee-ab4721aac2b1.jpg)

**Comment by mattthzu** [comment]
It happens when trying to check stats of Pokemon. I think it's because the bubble doesnt fit the screen

**Comment by Zarel** [comment]
Yeah I know what the problem is and will fix this ASAP.
