### ISSUE TITLE
/ds all need to be fix

### ISSUE THREAD

**Issue by sirKiraUzumaki** [smogon/pokemon-showdown#6772]
When I do /ds gen1, all there are onl about 50-60 mons but there are 151 mons as we know.
[Here](https://imgur.com/V4HrpUc) you can find the result of /ds gen1, all that I screenshot!

**Comment by urkerab** [comment]
`/ds gen1, all` excludes 89 illegal and 1 unreleased Pokémon by default. Use `/ds gen1, illegal, unreleased, all` to see all 151.

**Comment by Zarel** [comment]
In other words: `/ds` by default only shows Pokémon that are available in Sword/Shield.

If you wanted to show Pokémon that are available in Red/Blue/Yellow, the command you're looking for is `/ds1 all`.

**Comment by KrisXV** [comment]
Actually, no, doing `/ds1 all` is illegal since `all` as the sole parameter doesn't work. You need to add some other useless parameter like `/ds1 all, bst>0`.

**Comment by Zarel** [comment]
Weird, I tested it first and it worked for me.

**Comment by KrisXV** [comment]
Oh, I bet I know why it works.

Typing `/ds1 all` is the same as typing `/ds all, maxgen1`, so it automatically adds in another argument, while doing `/ds all` is just `/ds all`.
