### ISSUE TITLE
Errors Installing PS on Windows

### ISSUE THREAD

**Issue by AeonCaptain** [smogon/pokemon-showdown#6915]
When following install instructions for Windows, running node pokemon-showdown (in C:\Showdown, which is the PS folder), it gives this error:

c:\Showdown>node pokemon-showdown
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'c:\Showdown\pokemon-showdown'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by HoeenCoder** [comment]
This indicates that node was unable to find the `pokemon-showdown` file in your current directory, are you sure your in the correct directory? `pokemon-showdown` is in the root folder.

**Comment by AeonCaptain** [comment]
No, I don't see a pokemon-showdown file, I'll redownload the thing.
