### ISSUE TITLE
Urshifu-Rapid-Strike-Gmax has incomplete moveset

### ISSUE THREAD

**Issue by wrightjjw** [smogon/pokemon-showdown#6920]
It only has its learnset inherited from common moves for both fighting styles. I tried messing around with the pokedex entries and also adding an entry in learnsets.ts but to no avail.

As shown in the attached screenshots, Urshifu-Rapid-Strike gets Aqua Jet and Liquidation, but Urshifu-Rapid-Strike-Gmax does not. I'm specifically encountering the issue in building VGC teams but I've had it in other formats as well.
![Screenshot_20200626_235449](https://user-images.githubusercontent.com/20482282/85914912-93f86480-b808-11ea-8944-bccdba4490cd.png)
![Screenshot_20200626_235517](https://user-images.githubusercontent.com/20482282/85914917-98248200-b808-11ea-951b-f118ae9f7c52.png)

Also, this is really the first time I've interacted with this dev community - if this is the wrong place for a report like this please let me know, haha, but it didn't seem like this issue was listed anywhere else.

**Comment by KrisXV** [comment]
This is known, is already fixed, and will be live whenever the client is rebuilt next.
