### ISSUE TITLE
Room Owner group problem

### ISSUE THREAD

**Issue by theodelhay** [smogon/pokemon-showdown#7007]
Hello, when I install the server privately the roomowner group is below the Driver and Moderator grade. I think there is an error but I don't know where. (I haven't changed anything on my side).

Thank !

**Comment by Zarel** [comment]
Can you clarify "below"?

**Comment by Zarel** [comment]
Below in the user list? Below in the config file?

**Comment by theodelhay** [comment]
Sorry for my bad english

In the user list: http://prntscr.com/ti6pyi

**Comment by Zarel** [comment]
That's surprising. Can you copy/paste the protocol log? Use Chrome's debug console? (Ctrl+Shift+I on Windows, Opt+Cmd+I on Mac), then go to Console tab, and copy/paste everything here.

**Comment by theodelhay** [comment]
This ? 

``
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
(index):1 A cookie associated with a cross-site resource at http://pokemonshowdown.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
(index):1 A cookie associated with a cross-site resource at http://play.pokemonshowdown.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
client.js?d0efd37d:813 >> |/avatar swimmerf-gen4,1
client.js?d0efd37d:813 >> |/autojoin
client.js?d0efd37d:759 << |updateuser| Guest 1|0|101|{"blockChallenges":false,"blockPMs":false,"ignoreTickets":false,"hiddenNextBattle":false,"inviteOnlyNextBattle":false}
|customgroups|[{"symbol":"&","name":"Administrator","type":"leadership"},{"symbol":"★","name":"Host","type":"leadership"},{"symbol":"@","name":"Moderator","type":"staff"},{"symbol":"%","name":"Driver","type":"staff"},{"symbol":"#","name":"Room Owner","type":"normal"},{"symbol":"*","name":"Bot","type":"normal"},{"symbol":"☆","name":"Player","type":"normal"},{"symbol":"+","name":"Voice","type":"normal"},{"symbol":"whitelist","name":"Whitelist","type":"normal"},{"symbol":" ","name":null,"type":"normal"},{"symbol":"‽","name":"Locked","type":"punishment"},{"symbol":"!","name":"Muted","type":"punishment"}]
|formats|,LL|,1|Sw/Sh Singles|[Gen 8] Random Battle,f|[Gen 8] Unrated Random Battle,b|[Gen 8] OU,e|[Gen 8] OU (Blitz),e|[Gen 8] Ubers,e|[Gen 8] UU,e|[Gen 8] RU,e|[Gen 8] NU,e|[Gen 8] PU,e|[Gen 8] LC,e|[Gen 8] Monotype,e|[Gen 8] Anything Goes,c|[Gen 8] ZU,e|[Gen 8] 1v1,e|[Gen 8] CAP,e|[Gen 8] Battle Stadium Singles,1e|[Gen 8] Custom Game,c|,1|Sw/Sh Doubles|[Gen 8] Random Doubles Battle,f|[Gen 8] Doubles OU,e|[Gen 8] Doubles OU (Dynamax Level 0),e|[Gen 8] Doubles Ubers,e|[Gen 8] Doubles UU,e|[Gen 8] VGC 2020,1e|[Gen 8] 2v2 Doubles,c|[Gen 8] Metronome Battle,e|[Gen 8] Doubles Custom Game,c|,1|National Dex|[Gen 8] National Dex,e|[Gen 8] National Dex UU,c|[Gen 8] National Dex AG,e|,2|OM of the Month|[Gen 8] Cross Evolution,e|[Gen 8] Linked,e|,2|Other Metagames|[Gen 8] Balanced Hackmons,e|[Gen 8] Mix and Mega,e|[Gen 8] Almost Any Ability,e|[Gen 8] STABmons,e|[Gen 8] NFE,e|[Gen 8] Camomons,c|[Gen 8] Pure Hackmons,c|[Gen 8] Shared Power,c|[Gen 8] Tier Shift,c|[Gen 7] Balanced Hackmons,c|[Gen 7] Mix and Mega,c|,2|Pet Mods|[Gen 8] Megamax,e|[Gen 8] National Dex BH,e|[Gen 8] Optimons,c|[Gen 6] Gen-NEXT OU,8|,2|Randomized Metas|[Gen 8] Monotype Random Battle,f|[Gen 8] Challenge Cup 1v1,f|[Gen 8] Challenge Cup 2v2,d|[Gen 8] Hackmons Cup,f|[Gen 8] Doubles Hackmons Cup,d|[Gen 8] CAP 1v1,f|[Gen 7] Random Battle,f|[Gen 7] Random Doubles Battle,d|[Gen 7] Battle Factory,f|[Gen 7] BSS Factory,d|[Gen 7] Hackmons Cup,d|[Gen 7] Super Staff Bros Brawl,f|[Gen 7 Let's Go] Random Battle,d|[Gen 6] Random Battle,f|[Gen 6] Battle Factory,d|[Gen 5] Random Battle,f|[Gen 4] Random Battle,f|[Gen 3] Random Battle,f|[Gen 2] Random Battle,f|[Gen 1] Random Battle,f|[Gen 1] Challenge Cup,9|,3|RoA Spotlight|[Gen 2] Ubers,e|[Gen 4] UU,e|[Gen 6] Pure Hackmons,e|,3|Past Gens OU|[Gen 7] OU,e|[Gen 6] OU,e|[Gen 5] OU,e|[Gen 4] OU,e|[Gen 3] OU,e|[Gen 2] OU,e|[Gen 1] OU,e|,3|US/UM Singles|[Gen 7] Ubers,e|[Gen 7] UU,e|[Gen 7] RU,c|[Gen 7] NU,c|[Gen 7] PU,c|[Gen 7] LC,c|[Gen 7] Monotype,e|[Gen 7] Anything Goes,e|[Gen 7] 1v1,c|[Gen 7] ZU,c|[Gen 7] CAP,c|[Gen 7] Battle Spot Singles,1c|[Gen 7 Let's Go] OU,1c|[Gen 7] Custom Game,c|,3|US/UM Doubles|[Gen 7] Doubles OU,e|[Gen 7] Doubles UU,c|[Gen 7] VGC 2019,1c|[Gen 7] VGC 2018,1c|[Gen 7] VGC 2017,1c|[Gen 7] Battle Spot Doubles,1c|[Gen 7] Doubles Custom Game,c|,4|OR/AS Singles|[Gen 6] Ubers,c|[Gen 6] UU,c|[Gen 6] RU,c|[Gen 6] NU,c|[Gen 6] PU,c|[Gen 6] LC,c|[Gen 6] Monotype,c|[Gen 6] Anything Goes,c|[Gen 6] 1v1,c|[Gen 6] CAP,c|[Gen 6] Battle Spot Singles,1c|[Gen 6] Custom Game,c|,4|OR/AS Doubles/Triples|[Gen 6] Doubles OU,c|[Gen 6] VGC 2016,1c|[Gen 6] Battle Spot Doubles,1c|[Gen 6] Doubles Custom Game,c|[Gen 6] Battle Spot Triples,1c|[Gen 6] Triples Custom Game,c|,4|B2/W2 Singles|[Gen 5] Ubers,c|[Gen 5] UU,c|[Gen 5] RU,c|[Gen 5] NU,c|[Gen 5] PU,c|[Gen 5] LC,c|[Gen 5] Monotype,c|[Gen 5] 1v1,c|[Gen 5] GBU Singles,1c|[Gen 5] Custom Game,c|,4|B2/W2 Doubles|[Gen 5] Doubles OU,c|[Gen 5] GBU Doubles,1c|[Gen 5] Doubles Custom Game,c|[Gen 5] Triples Custom Game,c|,5|DPP Singles|[Gen 4] Ubers,c|[Gen 4] NU,c|[Gen 4] PU,c|[Gen 4] LC,c|[Gen 4] 1v1,c|[Gen 4] Anything Goes,c|[Gen 4] Custom Game,c|,5|DPP Doubles|[Gen 4] Doubles OU,c|[Gen 4] Doubles Custom Game,c|,5|Past Generations|[Gen 3] Ubers,c|[Gen 3] UU,c|[Gen 3] NU,c|[Gen 3] 1v1,c|[Gen 3] Custom Game,c|[Gen 3] Doubles Custom Game,c|[Gen 2] UU,c|[Gen 2] NU,c|[Gen 2] Custom Game,c|[Gen 1] Ubers,c|[Gen 1] UU,c|[Gen 1] OU (Tradeback),c|[Gen 1] Stadium OU,c|[Gen 1] Custom Game,c
client.js?d0efd37d:759 << |challstr|4|dfba184c08374402b9c9bfa8a98e004da987896d02cf64f908c95695601d45453e3ea6586bddec956683fd16100c309c700f7e9c1afa75a73ba49aa6231c427bcb367983ebd17fef15e82c05ed0754042ad57ce56b3bc2a6ba22138ceeec3932a72dccd8bea77ac17feb3f800ecd8f9671d40146de0ee25b6b92a5cefced72a1
client.js?d0efd37d:813 >> |/trn Distrib ★,0,dfba184c08374402b9c9bfa8a98e004da987896d02cf64f908c95695601d45453e3ea6586bddec956683fd16100c309c700f7e9c1afa75a73ba49aa6231c427bcb367983ebd17fef15e82c05ed0754042ad57ce56b3bc2a6ba22138ceeec3932a72dccd8bea77ac17feb3f800ecd8f9671d40146de0ee25b6b92a5cefced72a1,distrib,4,1594821598,localhost;6caf7e3946609aae933f9e58c968c552160c0e41d7a6586838785929bb198e2c7518a9c9b042bb7ad45b562d74c099d3806ace3c7f94ffb55014512467cb6ba4e8736f5124dabf4e4f0215f8e3f85411512082f8025ebf15e17addfcb07aab018aa71522fd2fdfcd77c6d0d52abc02eb1f0a8bcbbfd56bedf4f57d3e4c47c8991b1b4b84c25646ba0516c7204f7c35fc2c4bc9f18d25b97286e155e78306d15fbfb2cb8ec5481c484a4ff69bd1220a2a78eb7a3cdb3de9060c991c9f4644386ede16932095fb84e847c10e26827470740e01b749cb36ddbb8c8835cab0aa0e423480738a3c51b742176f7dcaee5972368916068ab78e3a98f69bd23538e54c4676183fc81afd729aea8fc1e4ddeac1bc07923642702852a95fbb179b7c5529df8e2b09eb6eebdf32c0792aef721657feda65cb57907bf4bdc07a53be58f122e2ebba65a7cd2ab82aecd1fa80fd3c1ec700b71ac14abbdf3590ecfe00272a8b5a2b77577ef07fda2b9b34545e96281f34782aaad7276a28489575756a5a870333bbd53ef798afa4c91351cc92c56425310be6a277fd7bb075eef2d3d58e694b40d0f815c23d214662e514d33df8a0c6a87ce2aea62d18ba39e3927fd33688b42b0217a3945e88c0e5eba7d9742ce14e1dc21e7d8e6e45da2611b2d9ccefb4da4ee644ec9478a0a3a8761ac044777d74ccd0ff8cd28c04db77c5da543f7953b475
client.js?d0efd37d:759 << |init|chat
|title|Lobby
|users|0
|:|1594821597

|raw|<div class="infobox"> You joined Lobby</div>
client.js?d0efd37d:759 << |updatesearch|{"searching":[],"games":null}
client.js?d0efd37d:759 << |updateuser| Distrib ★|1|swimmerf-gen4|{"blockChallenges":false,"blockPMs":false,"ignoreTickets":false,"hiddenNextBattle":false,"inviteOnlyNextBattle":false}
client.js?d0efd37d:759 << |j|#Distrib ★``

**Comment by Zarel** [comment]
Yes, thanks!

**Comment by Zarel** [comment]
(I deleted your message because it contains some private information.)

**Comment by theodelhay** [comment]
No problem, I hope I was able to help.

**Comment by Zarel** [comment]
This is the problematic line (h/t @mia-pi-git):

> `|customgroups|[{"symbol":"&","name":"Administrator","type":"leadership"},{"symbol":"★","name":"Host","type":"leadership"},{"symbol":"@","name":"Moderator","type":"staff"},{"symbol":"%","name":"Driver","type":"staff"},{"symbol":"#","name":"Room Owner","type":"normal"},{"symbol":"*","name":"Bot","type":"normal"},{"symbol":"☆","name":"Player","type":"normal"},{"symbol":"+","name":"Voice","type":"normal"},{"symbol":"whitelist","name":"Whitelist","type":"normal"},{"symbol":" ","name":null,"type":"normal"},{"symbol":"‽","name":"Locked","type":"punishment"},{"symbol":"!","name":"Muted","type":"punishment"}]`

For some reason, RO is getting sent as `type: "normal"` rather than `type: "leadership"`.

**Comment by mia-pi-git** [comment]
#7090 fixes this.
