### ISSUE TITLE
Undocumented message: "t:"

### ISSUE THREAD

**Issue by davidstone** [smogon/pokemon-showdown#7027]
https://github.com/smogon/pokemon-showdown/blob/master/PROTOCOL.md does not list a new message I have started receiving. As an example:

|t:|1595276262

It looks like it's just a Unix timestamp, but this is not a documented format for these types of messages. battle-gen1ou-1154689141 is an example battle that shows these messages.

**Comment by scheibo** [comment]
Hi, it is documented in the [SIM-PROTOCOL as it is a battle progress message](https://github.com/smogon/pokemon-showdown/blob/master/sim/SIM-PROTOCOL.md#battle-progress).

**Comment by davidstone** [comment]
Thank you
