### ISSUE TITLE
Assertion is stale

### ISSUE THREAD

**Issue by SubaRamesh** [smogon/pokemon-showdown#7064]
I am just learning how to use websocket and create a bot. After receiving the assertion and sending the |/trn USERNAME,0,ASSERTION , I always receiev a message that says:

|NAMETAKEN|USERNAME|Your assertion is stale. This usually means that the clock on the server computer is incorrect. If this is your server, please set the clock to the correct time. 

I have never messed with the clock on my device and I don't know how to adjust any of that in the script, so I do not understand why it would be stale. I also did not try to change my username, have I successfully logged in? Can I ignore this message?

**Comment by Zarel** [comment]
Heh, I'm glad we got that figured out. It looks like we need better error messages, though.
