### ISSUE TITLE
Play button on Desktop client broken

### ISSUE THREAD

**Issue by Meshugah** [smogon/pokemon-showdown#7075]
To reproduce:
- Navigate to https://pokemonshowdown.com/
- "Play" button on the top navbar redirects to page "about:blank#blocked"

Other details:
- "Play Online" button still works; Navigates to the 'play.pokemon.com' site.

**Comment by KrisXV** [comment]
This was fixed by @AnnikaCodes in https://github.com/smogon/pokemon-showdown-client/pull/1577
