### ISSUE TITLE
Creating groupchats is not working

### ISSUE THREAD

**Issue by AlphaWind** [smogon/pokemon-showdown#7131]
Everytime I try to create a groupchat on my test server this error message appears: `Room titles can't contain any of: ,|[-`

**Comment by AnnikaCodes** [comment]
This is a known bug being worked on in https://github.com/smogon/pokemon-showdown/pull/7123#issuecomment-667632714.

**Comment by Zarel** [comment]
This should be fixed now that #7123 is merged.
