### ISSUE TITLE
Validator claims gen 8 mons with insufficient IVs are gen 6 legendaries

### ISSUE THREAD

**Issue by Lusamine** [smogon/pokemon-showdown#7302]
Any set for a Pokemon that has fewer than the expected number of 31 IVs claims that it needs more due to being a gen 6 legendary.  Obviously, Dracovish is not gen 6 or a legendary.   I think this is hard coded in for every later-gen Pokemon and the best way to fix it may not be as simple as changing the text in the case of Pokemon that have different numbers of expected 31 IVs.

This set produces the error in Gen 8 Anything Goes:

Dracovish @ Aguav Berry  
Ability: Water Absorb  
EVs: 252 HP  
IVs: 0 HP / 0 Atk / 0 Def / 0 SpA  
\- Body Slam

![image](https://user-images.githubusercontent.com/30205550/92108735-779b1a00-edad-11ea-9579-e3c37c3db40e.png)

**Comment by Zarel** [comment]
@TheImmortal Your new message still says "legendary". What phrasing should we use instead?

**Comment by Zarel** [comment]
"Because of the way it's obtained"?

**Comment by Zarel** [comment]
"Because it's unbreedable"?

**Comment by TheImmortal** [comment]
> @TheImmortal Your new message still says "legendary". What phrasing should we use instead?

It doesn’t. I added the gen fossils to exceptions. The message is fine and doesn’t need to be changed.

**Comment by Zarel** [comment]
Oh, I misread the code earlier. I understand how it works now, there's no problem with it.
