### ISSUE TITLE
Bug with Urshifu - "Possible Illusion"

### ISSUE THREAD

**Issue by MarcinInDisguise** [smogon/pokemon-showdown#7303]
Today while playing Gen 8 Singles OU I found something weird. After defeating Urshifu-Rapid-Strike I saw that his icon indicates that he is still alive. Upon hover, it displays information about "Possible Illusion". I checked a little bit in source code, but I didn't found anything suspicious. 

<img width="304" alt="ursh" src="https://user-images.githubusercontent.com/26366161/92121978-329dd480-edfb-11ea-8008-5b1dab2af4c1.png">

Replay 
[Gen8OU-2020-09-03-1blue-s13711.zip](https://github.com/smogon/pokemon-showdown/files/5168903/Gen8OU-2020-09-03-1blue-s13711.zip)

**Comment by Zarel** [comment]
Thanks for the replay! That should make it much easier to figure out what's wrong.

**Comment by TheImmortal** [comment]
I believe this is fixed now with https://github.com/smogon/pokemon-showdown-client/commit/a9d4d5e9e9a58e4c8f53d9275a1a0b5be59bbf76
