### ISSUE TITLE
Feature request: A training mode/Continuing battle from replay

### ISSUE THREAD

**Issue by grenvol** [smogon/pokemon-showdown#7336]
To practice, It would be awesomely helpful to have a training mode or a way to continue battle from a replay (like If I want to continue a battle from turn 30 with a friend, I should be able to).

The easiest way to implement this would be to allow custom pp counts and custom hp in the teambuilder for custom games.

**Comment by Zarel** [comment]
This is already possible using the commands `/exportinputlog` and `/importinputlog`.

It can't be done from replays for teambuilder-based format because you need permission from the other player to use their team. But you can ask permission using `/exportinputlog` at the end of the battle.

**Comment by Zarel** [comment]
(Closing, but feel free to reopen if I've misinterpreted your request or something.)
