### ISSUE TITLE
Hey You Have to work on style of Ps!

### ISSUE THREAD

**Issue by arcreaco** [smogon/pokemon-showdown#7395]
that means that you have to add better CSS in the server

**Comment by Zarel** [comment]
You don't seem to understand what GitHub is for. I've blocked you, but this is not intended as a punishment, but rather as protection against further accidental misuse. If you ever want to use GitHub for its intended purpose (to plan and coordinate development), feel free to e-mail us at `staff@pokemonshowdown.com` and we can discuss unblocking you.
