### ISSUE TITLE
Galarica Cuff missing from the data/items.ts file

### ISSUE THREAD

**Issue by ivanlonel** [smogon/pokemon-showdown#7408]
### EDIT: as pointed out by @monsanto, only Galarica Cuff is actually missing from items.ts.
Dubious Disc is in there, but is incorrectly spelled Dubious Disk in pokedex.ts

___

I was playing around with Smogon and Pokémon Showdown data and found 25 items that are mentioned either in other files from the pokemon-showdown/data folder or in Smogon sets, but are not currently in the pokemon-showdown/data/items.ts file.

If I understand correctly, that file is the main source of item-related info in Pokémon Showdown, so I believe at least some of these items belong in there:

- Banettite
- Cheri Berry
- Chill Drive
- Claw Fossil
- Colbur Berry
- Cornn Berry
- Damp Rock
- Dubious Disk
- Eviolite
- Galarica Cuff
- Hard Stone
- Jaw Fossil
- Kebia Berry
- Kee Berry
- Odd Incense
- Payapa Berry
- Pecha Berry
- Ring Target
- Rowap Berry
- Rusted Shield
- Silk Scarf
- Tapunium Z
- Tart Apple
- Water Gem
- Zap Plate

**Comment by monsanto** [comment]
All of these except Galarica Cuff are currently in the file, might want to double check how you're searching. @Marty-D ?

**Comment by ivanlonel** [comment]
Oh, this is embarassing... when I went to search the items in the file outside of my program to double check it wasn't a bug in my code, I mistakenly looked in the intermediate json file I had generated, instead of looking in the actual typescript file.

Turns out my algorithm for extracting data from the data/*.ts files was to blame. Never use a regex to do a parser's job, I guess. Sorry for wasting your time on looking into that.

Anyway, the "Dubious Disk" case is a typo in data/pokedex.ts (Porygon-Z's "evoItem" property). The correct name would be Dubious Disc, ended in 'C', as it's correctly spelled in the items.ts file.

I suppose I should change the issue's title to reflect the fact that only one of those items is actually missing.

**Comment by Zarel** [comment]
I remember Galarica Cuff being the main barrier to not being able to add a unit test for "item must exist" to the `evoItem` field.

Should we commit to including evolution items in `items.ts`?

**Comment by Marty-D** [comment]
I think @KrisXV asked if he could add Galarica Cuff a few days ago and I forgot to reply. Consensus is yes! I'll handle the sprite.

**Comment by ivanlonel** [comment]
Added pull request #7410 for Dubious Disc typo correction.
