### ISSUE TITLE
Max Flare base power listed as 100 instead of 10

### ISSUE THREAD

**Issue by InvalidOS** [smogon/pokemon-showdown#7533]
Probably a typo, not much else to say here

**Comment by PartMan7** [comment]
That isn't a typo - the games store Max Flare's (and only Max Flare's) BP as 100, while all others are 10 by default.

**Comment by Zarel** [comment]
To be fair, PS doesn't need to _display_ them that way just because the games store them that way. We might want to consider displaying base power for Z/Max moves as `–` if they have dynamic damage.
