### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [smogon/pokemon-showdown#7602]
The README file in this repo has a bad link

Status code [404:NotFound] - Link: https://github.com/smogon/pokemon-showdown/blob/master/sim/COMMANDLINE.md

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by Zarel** [comment]
Thank you!
