### ISSUE TITLE
Add isNonstandard to pokedex data

### ISSUE THREAD

**Issue by GeoDaz** [smogon/pokemon-showdown#7616]
Could you add please : isNonstandard to pokedex datas in  /data/pokedex.ts for export ?
CAPmons, Pokestars and Missingno are non standard 😄

**Comment by Zarel** [comment]
I actually agree that it makes more sense in `pokedex.ts` than `formats-data.ts`.

But you will always need to use the `Dex` API for full information. `Past` and `Future` are only filled in dynamically.
