### ISSUE TITLE
Vulnerability? Or I'm wrong?

### ISSUE THREAD

**Issue by Makasimka** [smogon/pokemon-showdown#7641]
Hello! I noticed this in your code:
side.ts -> clearChoice

You clear all the data, but then, just below, you give an error that: "Can't move: You can't Z-move more than once per battle"

It turns out that after I cancel any action in PS, I have access to reuse: Z-move, Mega-evol, and so on?

Either I misunderstand something, or is this really a vulnerability?

**Comment by xfix** [comment]
I'm not seeing the issue. `clearChoice` clears the previous choice before parsing a new one. It doesn't mean that it allows using Z-move more than once.

Could you provide a replay or something showing the issue?

**Comment by Makasimka** [comment]
Your check for the use of z-moves and mega-evolutions comes right after clearChoice.

This means that in subsequent requests I can safely use zMove / mega / ultra / dynamax, simply because all this is cleared before a new request is processed.

**Comment by xfix** [comment]
Oh, I see where the confusion comes from. The code in `chooseMove` handles the case where the player in double battle Z-moves both Pokemon. If Z-move was already used during a battle then an option to Z-move is simply not available.

**Comment by Makasimka** [comment]
You, below, do the following check:

if (zMove && this.choice.zMove) {
return this.emitChoiceError (`Unable to move: you cannot move along the Z axis more than once per battle`);
}

After cleaning, it by itself will not be relevant, and if you limit only in the "client", then the system is easy to "trick" by changing your JS, which will allow you to use Z-Move several times per battle.

**Comment by xfix** [comment]
This code is specifically to prevent using Z-move twice in a turn as at the point of making a choice in a double battle Z-move wasn't used.

However, once a move has been actually used, using Z-moves is prevented by `canZMove` property.

**Comment by xfix** [comment]
I think I will close the issue unless you can show a replay showcasing the issue.

**Comment by Zarel** [comment]
For future reference, (especially if you're having trouble understanding our explanations), it's probably useful to actually test your guesses in a game to see if you're right. The `/choose` command is available for this.
