### ISSUE TITLE
Cannot add Pokémon on older Teams on PC client

### ISSUE THREAD

**Issue by FusselTeddy** [smogon/pokemon-showdown#7699]
I just wanted to edit some older Teams on the client version of PS, but the button "+ Add Pokémon" doesn't exist, even on a team with only 2 Pokémon...
If I create a new team everything works fine, the button is there, I can do some battles and edit the team afterwards. If i close PS and open it back up, I can't add Pokémon to any existing Team...

I already tried reinstalling it, but it didn't help. I clean cookies from time to time in my web browser an don't want to lose every team because of that, that's why I'm using the PC client version.

Edit: I'm on Windows 10 and everything was working fine about 2 weeks ago

![Help](https://user-images.githubusercontent.com/31009374/99195515-8c6d3400-2786-11eb-8438-523663677272.png)

**Comment by Zarel** [comment]
This should be fixed by https://github.com/smogon/pokemon-showdown-client/issues/1688

Can you tell me if it isn't?

**Comment by FusselTeddy** [comment]
It's fixed now, thanks 😄
