### ISSUE TITLE
"Alphabet Cup Move Legality" has not been updated to include the passing of the Prevo Clause

### ISSUE THREAD

**Issue by alaserdolphin** [smogon/pokemon-showdown#7735]
The validator rule for Alphabet Cup only validates moves that are sharing the same starting letter of the Pokemon itself and not its previous evolutions.

[Thread with poll](https://www.smogon.com/forums/threads/alphabet-cup.3672756/)

[Link to original commit](https://github.com/smogon/pokemon-showdown/commit/e1c96f8a74b96ed57b7fbf3c6aa600495c461cd0)

**Comment by KrisXV** [comment]
Done in https://github.com/smogon/pokemon-showdown/commit/2b510d050d0df335924dedd3d2a63561037154ec
