### ISSUE TITLE
Getting Access Denied from "/tour create"

### ISSUE THREAD

**Issue by AndreJorgeLopes** [smogon/pokemon-showdown#7763]
Normal server setup

**Comment by AnnikaCodes** [comment]
Have you given yourself Administrator rank (`&`)?

**Comment by AndreJorgeLopes** [comment]
Yes, there is a print of the screen if that helps.
http://prntscr.com/vv35em

**Comment by Zarel** [comment]
My guess is that your permissions setup is misconfigured. Can you re-copy the usergroup setup from `config-example`?

**Comment by DaWoblefet** [comment]
I used to be able to reproduce this but cannot anymore. From a fresh clone of the server, I created a config.js from config-example.js, created a usergroups.csv with myself as administrator, and was able to run commands just fine.
