### ISSUE TITLE
Is `BattleStream.awaitingPush` ever used?

### ISSUE THREAD

**Issue by szymonWojdat** [smogon/pokemon-showdown#7764]
Hey I've been playing around with your stream API that I installed via npm. I was trying to figure out how do I ever know if the `BattleStream` is still processing my previous input or if it's waiting for my next input and I came across `BattleStream.awaitingPush` but it's always `false` and doesn't ever seem to be set to `true` in the codebase (after being set to `false` in `ReadStream.constructor`. 

- Is it ever used? 

    - If no, then is there any other way of figuring whether the `BattleStream` is waiting for my input (without relying on any timeout)?

**Comment by Zarel** [comment]
Hi! From a grep of the codebase, it looks like `awaitingPush` is not currently used. I'll remove it.

The stream APIs are async for convenience, but `BattleStream` is synchronous, so I believe the answer to "is the `BattleStream` still processing input?" is always "no".

You never need to wait to input, anyway. You can push an entire input log into a `BattleStream` in a single write.

If you need to know what the stream is waiting for, the most recent `|request|` message should always make that clear. You can clear out requests after sending choices, which should make your state always-consistent.

Is that enough information to work with?

**Comment by Zarel** [comment]
If you ever need to synchronously poll request state, they can be found in `stream.battle.p1.activeRequest` and `stream.battle.p2.activeRequest`, but in theory you should never have a need to do this directly.

**Comment by szymonWojdat** [comment]
Thanks for your reply! This is very informative. One more question:

> `BattleStream` is synchronous

From what I've seen, `BattleStream.write()` is indeed synchronous but `BattleStream.read()` is async, at least those are the two methods used in `BattleTextStream`. My idea was to send each input only once the output to my previous input has been received from the `BattleStream`, so my guess is that I need to do it in an asynchronous way, ie. via `.then(...)` etc. (or use `stream.battle.p1.activeRequest`) correct?

**Comment by Zarel** [comment]
Heh, that's an eminently sensible use-case that I never thought of supporting. I will have to support that properly at some point.

For now... you can actually synchronously grab the results directly from the read buffer. Synchronously immediately after `stream.write`, `stream.buf` should be an array of all the responses, which you can set `stream.buf = []` after you grab it to simulate a read. That will constitute a synchronous version of `stream.read()`.

I don't know if I'll support that long-term, but it should work for now.

**Comment by szymonWojdat** [comment]
This is exactly what I've been looking for, thanks so much! The buffer always contains all the previous messages (which is not an issue for me), so if you're ever planning to add a synchronous stream-like read method, feel free to hit me up and I'll do my best to contribute, though I'm not a JS ninja.

**Comment by Zarel** [comment]
> always contains all the previous messages

Yes, that's why I'm saying to set `stream.buf = []` after reading it, to clear previous messages. :p I suppose it's fine if you don't want to do that, though.

**Comment by szymonWojdat** [comment]
Oh I must've missed that haha. That's actually perfect :)
