### ISSUE TITLE
Ability Berserk does not activate if hit with a non Sheer Force single strike move if holding a berry that brings the pokemon back above 50% health

### ISSUE THREAD

**Issue by dashmurphy** [smogon/pokemon-showdown#7804]
Based on research on Bulbapedia as well as battling ingame, the ability Berserk does not perform correctly on the VGC2021 ladder.
From Bulbapedia:
"If the HP of a Pokémon with Berserk drops below half but is about to be restored to above half due to a held item such as a Sitrus Berry, Berserk will activate before the HP is restored. "

Here is a replay where this behavior is observed(turn 5):
https://replay.pokemonshowdown.com/gen8vgc2021-1243668070-nsxpfc2k75eqmr6zrlhp4k45sweuznlpw

**Comment by DaWoblefet** [comment]
This was fixed in https://github.com/smogon/pokemon-showdown/pull/8147
