### ISSUE TITLE
Can't run /tour new (bug)

### ISSUE THREAD

**Issue by LoryColo** [smogon/pokemon-showdown#7872]
I set up a private server and created the usergroups.csv file, setting it up as follows: `Padron touch me,&`
i can't run the /tour new command unless i am a room owner, which is strange. I already talked to DaWoblefet about it and he seems to be having the same problem on his localhost

**Comment by Zarel** [comment]
I can reproduce this. It looks like defaults are a bit wonky.

**Comment by Zarel** [comment]
You'll need to manually add the `tournaments` permission to `config.js` like the commit does to `config-example.js`.
