### ISSUE TITLE
Silvally not actually learning Water and Fire Pledge

### ISSUE THREAD

**Issue by Amaterasu5** [smogon/pokemon-showdown#7910]
So I think, due in part to the SWSH dataminers, fire pledge and water pledge are listed as being in Silvally's moveset. There's an issue believed to have been started in USUM where Silvally technically has these moves legal in moveset but it's programmed to be impossible to attain them in-game. If you try to teach either of these moves to Silvally at the pledge tutor, he will **only** give the option of grass pledge no matter what, even if Silvally is holding a Water Memory, and will give you no option at all if you already know Grass Pledge.

This is easily reproducible, but I've added pictures as well. 

![OriginalMoveset](https://user-images.githubusercontent.com/4542763/104258065-0b57b380-543c-11eb-8f0b-10a601f258a1.PNG)
![HoldingWaterMemory](https://user-images.githubusercontent.com/4542763/104258060-098df000-543c-11eb-8010-72676b1919fb.PNG)
![GrassPledgeOnlyOption](https://user-images.githubusercontent.com/4542763/104258058-08f55980-543c-11eb-938a-4d8b04543420.PNG)
![AfterLearningGrassPledge](https://user-images.githubusercontent.com/4542763/104258054-07c42c80-543c-11eb-945c-f4f11c626a87.PNG)
![KnowingGrassPledge](https://user-images.githubusercontent.com/4542763/104258061-098df000-543c-11eb-9144-2e889362ac6f.PNG)

If trying to stay true to cart, these moves should be removed from Silvally's true learnset.

**Comment by urkerab** [comment]
I remember this happening for USUM, and the moves have since been removed from the USUM learnset, so I guess it's just a case of removing them from the SwSh learnset too.

**Comment by TheImmortal** [comment]
3fd5c4b1dc53ee6bb016e8e70aa506334facc074

**Comment by urkerab** [comment]
(IIRC you can include "fixes #7910" or some such in the commit message to automatically link and close this issue. See https://github.blog/2013-01-22-closing-issues-via-commit-messages/)

**Comment by Amaterasu5** [comment]
thanks for the fix!
