### ISSUE TITLE
[Question] How to set up no team preview?

### ISSUE THREAD

**Issue by artiblaster** [smogon/pokemon-showdown#7918]
I understand there is a Custom Games option available in the game type menu after you challenge someone. However when I do this, I'm not presented with any actual options for customizing the match. Could anyone tell me the proper process?

I've seen a ton of replays with the 'Custom Game (No Team Preview)' modifier and it seems like very basic feature, so I feel like it must be possible.

Thank you, kind strangers.

**Comment by Distrib-ps** [comment]
Hey !
To fight someone in a custom game with this rule:
`/challenge [USER], [Gen 8] Custom Game @@@ !Team Preview`
For more information :
Type `/battlerules ` in chat OR https://github.com/smogon/pokemon-showdown/blob/master/config/CUSTOM-RULES.md

**Comment by Zarel** [comment]
"Custom Game (No Team Preview)" was previously an option in the drop-down. It's currently not there anymore, so you'll need to use chat commands to achieve it.

The plan is to add actual options instead of making you use the chat command, but we're not there yet.
