### ISSUE TITLE
Limiting server access to specified accounts

### ISSUE THREAD

**Issue by LoryColo** [smogon/pokemon-showdown#7925]
Is there a way to have a whitelist and enable server access to users on that whitelist but not to anyone else?

**Comment by Nekurone** [comment]
If you need help with this, you probably shouldn't be running your own server.

Though, [Npm has a neat ip whitelist tool found here](https://www.npmjs.com/package/ip-whitelist) https://www.npmjs.com/package/ip-whitelist

**Comment by mia-pi-git** [comment]
For what it's worth, a module shouldn't be necessary - simply add a loginfilter (in config/config.js or in a chat plugin) that checks user ips / names and disconnect them if they aren't whitelisted.

**Comment by Slayer95** [comment]
> If you need help with this, you probably shouldn't be running your own server.
Though, Npm has a neat ip whitelist tool found here https://www.npmjs.com/package/ip-whitelist

Had you read the issue you would have noticed that the request is an account whitelist, not an IP whitelist.

We need to define what's understood for "server access". IMO, that includes:
1. Reading chat rooms
2. Sending messages to chat rooms
3. Laddering
4. Private messages
5. Private challenges
6. Viewing the list of rooms
7. Issuing coomands other than ``/trn``

All those seven points should be restricted not only for non-whitelisted users (for which as @mia-pi-git says the solution is disconnecting them), but also for Guests. That's the real depth of this feature request, and I'd say the way forward is a config preset.

**Comment by Slayer95** [comment]
> Viewing the list of rooms

Just taking on this point, the room list should start hidden, and the server should send it as soon as the user logs in. This might sound obvious, but in fact PS currently doesn't send the room list on rename. A prime example of that would be that logging as ``#development`` room auth doesn't allow you to see the room listed under ``Official chat rooms`` unless you send ``/cmd rooms``.

**Comment by Zarel** [comment]
It depends on what you mean by "allowed".

At a basic level, you can set the Config settings `chatmodchat`, `battlemodchat`, and `pmmodchat` to `+`, at which point the voice rank will function as your whitelist. This is the intended use of these settings.

**Comment by monsanto** [comment]
Old issue, this is probably doable in a config hook
