### ISSUE TITLE
Poltergeist item check being applied to wrong move.

### ISSUE THREAD

**Issue by curtdissel** [smogon/pokemon-showdown#7971]
Replay:
https://play.pokemonshowdown.com/battle-gen8randomdoublesbattle-1272791711-xvlggl6vtj76uzbrosiooy1jjwzucozpw

Happens on final turn.
Opponent uses Ice Punch, but it fails. That should never happen for Ice Punch.

**Comment by cheesetheorange** [comment]
not sure if i should be necroing this but the dusknoir targeted its (fainted) ally slot which is why the move failed, i believe that is intended behavior

**Comment by DaWoblefet** [comment]
> Replay:
> https://play.pokemonshowdown.com/battle-gen8randomdoublesbattle-1272791711-xvlggl6vtj76uzbrosiooy1jjwzucozpw
> 
> Happens on final turn.
> Opponent uses Ice Punch, but it fails. That should never happen for Ice Punch.

As cheesetheorange says, this was because you misclicked and targeted your empty partner slot. Not a bug!
