### ISSUE TITLE
Add a "reset turn" button in casual match

### ISSUE THREAD

**Issue by eliasreid** [smogon/pokemon-showdown#7997]
Would be nice to be able to undo a turn if both players agree to it in a casual match.

Sometimes when I'm playing with a friend and one of us misclicks, we would both prefer to allow the "misclicker" to re-select their move.

**Comment by Zarel** [comment]
This is the wrong place for suggestions – please go to https://psim.us/suggestions

Also: This is already supported by `/exportinputlog`, deleting the turn, and then `/importinputlog`.
