### ISSUE TITLE
How to deep clone stream.battle?

### ISSUE THREAD

**Issue by UfukE** [smogon/pokemon-showdown#8105]
Hello! I've been trying to learn the Pokemon Showdown Simulator api for the past few days. I was wondering if there is any way to deep clone `stream.battle` object? Basically what i am trying to achieve is to simulate a new turn from any current turn in the battle.

**Comment by Zarel** [comment]
Hi! We have two different ways of cloning a battle simulation.

1. Export the input log `stream.battle.inputLog.join('\n')` and import it into a new battle stream
2. Serialize and deserialize the battle with the relevant functions from `state.ts`

The input log method is easier to use, and has better performance if you're mostly just backing up state and rarely actually using it. The serialization method has better performance if you're actually doing the full clone very often.

**Comment by UfukE** [comment]
Ah thanks, `stream.battle.toJSON` and `Battle.fromJSON` works perfectly.
