### ISSUE TITLE
Legendary & mythical flags

### ISSUE THREAD

**Issue by darrenswhite** [smogon/pokemon-showdown#8141]
Hi,

Would it be possible to add flags to `data/pokedex.ts` to indicate whether a Pokémon is legendary or mythical?

I'd be happy to create a PR if this is acceptable.

Thanks.

**Comment by Zarel** [comment]
Honestly, this is a good idea. Is there any reason why we don't already do this?

**Comment by darrenswhite** [comment]
Not sure. I was looking around for a flag and couldn't find one. The only logic for determining legendary/mythical status I could find was here: https://github.com/smogon/pokemon-showdown/blob/afb15b82f0bdc61f83477e8bb2d4a1f4473e28a9/sim/team-validator.ts#L797

That led me to PokeAPI which has both flags (`is_legendary` and `is_mythical`).

Via PokeAPI: https://pokeapi.co/api/v2/pokemon-species/151
Via PokeAPI GH: https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species.csv

**Comment by Zarel** [comment]
There's a long ongoing discussion on Discord, if you'd care to join ( https://psim.us/devdiscord ).

There seems to be lots of contention on how you define "legendary" and "mythical". Apparently the terms can be ambiguous.

**Comment by xInstruct** [comment]
Delayed comment but stealing this :^)

**Comment by xInstruct** [comment]
sorry lol

**Comment by Zarel** [comment]
Done in #8142

Wow, this took an entire month due to a lot of delays, most recently in #8218. But oh well, it's done now!

**Comment by Zarel** [comment]
(But do tell if you need a new NPM package, otherwise that'll probably be a bit longer.)
