### ISSUE TITLE
Is it trivial to pull team information from replays?

### ISSUE THREAD

**Issue by victor-z-xiong** [smogon/pokemon-showdown#8217]
Is it possible for replays to show the pokemon's full moveset, EV spread, nature etc. when hovering over the sprite?

I wanted to try some of my old teams, but don't have anything saved from the old browsers.

**Comment by xfix** [comment]
Replays intentionally don't show this information.

**Comment by victor-z-xiong** [comment]
So all this information is saved, just not displayed? Why is that the case?

**Comment by Zarel** [comment]
Privacy reasons. We could show you your own team information, I suppose. That would need to be coded. Until then, feel free to open a help ticket for it.
