### ISSUE TITLE
Wrong description for Tail Glow in gen 4  

### ISSUE THREAD

**Issue by VMoM** [smogon/pokemon-showdown#8221]
Hello, I noticed that in gen 4 the description of Tail Glow said that this move raises the special attack by 3, but it's only by 2 on gen 4.
Thanks for making this awesome game!

**Comment by DaWoblefet** [comment]
All oldgen descriptions are wrong. It's due to an error in the client build script (it's correct server-side).

**Comment by DaWoblefet** [comment]
This was fixed by Karthik99999 in https://github.com/smogon/pokemon-showdown-client/pull/1786
