### ISSUE TITLE
IVs Don't export

### ISSUE THREAD

**Issue by jakehus8** [smogon/pokemon-showdown#8243]
Hi, I am trying to create custom sets with specific IVs to the pokemon I've caught. However, when I try to export the pokemon, the IVs don't export with it making me have to enter each of them in one by one everytime.

**Comment by DaWoblefet** [comment]
What do you mean? Seems fine when I try it:

![image](https://user-images.githubusercontent.com/23667022/117196651-5a8b7080-adac-11eb-8214-c3c758c4aca9.png)

![image](https://user-images.githubusercontent.com/23667022/117196667-60815180-adac-11eb-994a-25c0cb6f04d8.png)

![image](https://user-images.githubusercontent.com/23667022/117196683-670fc900-adac-11eb-9c3c-280af66fe6ce.png)

**Comment by jakehus8** [comment]
Sorry for not clarifying. I meant in the damage calculator if you try to change the ivs then export.

**Comment by DaWoblefet** [comment]
You'll want to report that in the [damage calculator bug reports thread](https://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-damage-calculator.3593546/) then, or create an issue on [their repository](https://github.com/smogon/damage-calc/issues). This is for the Pokemon Showdown server.
