### ISSUE TITLE
Getting user requesting validation

### ISSUE THREAD

**Issue by RogueStatistician** [smogon/pokemon-showdown#8321]
I wanted to try and implement a player specific validation based on the pokemons a person has access to in his "box". I have the info about the boxes in an external website and I can expose an API to get that but I don't know if there's a way to get a reference to the player requesting validation to authenticate in the API accordingly. Any suggestion?

**Comment by Zarel** [comment]
Yeah, unfortunately, the team validator definitely doesn't have access to that information. You'd have to wire it in from call sites.

**Comment by Zarel** [comment]
Probably `Ladder#prepBatlte` in `server/ladders.ts` is the best place to achieve this.

**Comment by monsanto** [comment]
No response.
