### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by DoomSlayer-cm** [smogon/pokemon-showdown#8353]
Can you make it so that you can download the game directly from github

**Comment by mia-pi-git** [comment]
You... can download the code from GitHub. Click the green "code" button on the main page and then click "download zip".
But, either way, Issues is for code bugs, not suggestions. See [here(https://www.smogon.com/forums/forums/suggestions.517/)] for suggestions.

**Comment by Zarel** [comment]
You really need to be much more specific about exactly what you want to download here. The README describes all the different things you can do with the code, all of which link to instructions for how to do the thing you want to do.

**Comment by DoomSlayer-cm** [comment]
Can u have a download for Pokemon showdown that's executable, like a downloadable game?

**Comment by xfix** [comment]
> Can u have a download for Pokemon showdown that's executable, like a downloadable game?
> […](#)
> Sent from my iPhone
> On Jun 2, 2021, at 7:02 PM, Guangcong Luo ***@***.***> wrote: You really need to be much more specific about exactly what you want to download here. The README describes all the different things you can do with the code, all of which link to instructions for how to do the thing you want to do. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

If you visit https://pokemonshowdown.com/ on a supported platform you can get a downloadable client for Windows and macOS.

**Comment by Zarel** [comment]
Yes, that already exists, the link is on https://pokemonshowdown.com/

**Comment by DoomSlayer-cm** [comment]
I mean a download of that from GitHub because I wanna play this on a school computer but PS is blocked

**Comment by xfix** [comment]
> I mean a download of that from GitHub because I wanna play this on a school computer but PS is blocked
> […](#)
> Sent from my iPhone
> On Jun 7, 2021, at 8:44 AM, Guangcong Luo ***@***.***> wrote: Yes, that already exists, the link is on https://pokemonshowdown.com/ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

If your school blocks Pokemon Showdown then having a Pokemon Showdown client is pretty much worthless considering it needs to connect to the Pokemon Showdown server which is blocked.

**Comment by DoomSlayer-cm** [comment]
Can you make an alternate server for unblocked matches?

**Comment by Zarel** [comment]
No. While technically possible, it would cost plenty of money, be difficult to let people know it exists, and would end up get blocked as well, anyway.

**Comment by DoomSlayer-cm** [comment]
Well I know it exists, so I can refer it to friends since most of them have school computers. Also, maybe they get blocked because you get word out to teachers
