### ISSUE TITLE
Running PS Server in a stateless environment

### ISSUE THREAD

**Issue by szymonWojdat** [smogon/pokemon-showdown#8375]
Hey I've been playing around with deploying PS in Google App Engine, which is a serverless platform and only supports file reads in its local file system. Does anyone have a list of files that PS writes to while being ran, so that I can move them to a separate file server to ensure that I don't lose my PS state and that App Engine doesn't break (in case it tries writing to a read-only file)? One example below:
```
Error: EROFS: read-only file system, open '.config-dist/sourceMaps/formats.js.map'
```
I'd guess this would apply to any stateless platform.

**Comment by szymonWojdat** [comment]
Just found out it's mostly config directory. If anyone can confirm nothing gets written anywhere else, that'd be great.

**Comment by mia-pi-git** [comment]
config/ and logs/ are the main things we write to.

**Comment by szymonWojdat** [comment]
thanks!

**Comment by Zarel** [comment]
We also have `databases/` for databases, and the compile step writes a bunch of stuff into dist directories.

If you precompile everything, I'm 80% sure `config/`, `logs/`, `databases/`, and `.config-dist/` cover everything.

**Comment by szymonWojdat** [comment]
Very nice thanks! Anything pre-build should be fine, post-build writes are the ones bothering me the most.

A small tangent while we're at it - is there any chance to support custom css for unofficial servers? I'd assume it's not there for security reasons. At least background image customization would be nice, I can help take a look myself if that helps :)

**Comment by monsanto** [comment]
It sounds like the main issue was addressed. (I think it would be a good idea if we had more separation between code and data...)
