### ISSUE TITLE
Trying to Generate Random Team to PokePaste

### ISSUE THREAD

**Issue by enlighten1self** [smogon/pokemon-showdown#8385]
I have a discord bot that uses this API and can run a command that will generate a random team.

the output is an export format, but is there a way for it to be a pokepaste link instead?

also i am having a hard time validating teams that are in export format as when i try to import to Json, the objects do not fill in correctly or i get errors... but i can make another issue for that. 

thank you in advance, this is a great API, i am learning as i go!!

**Comment by mia-pi-git** [comment]
Hi! We do not support outputting a PokePaste URL, as that application is separate from ours (and we have no need of it.) You would have to manually upload the team to PokePaste and get a URL via their API. (POST to https://pokepast.es/create with title, paste, and author keys.) 
Have a nice day!

**Comment by enlighten1self** [comment]
regarding team validation, does this work for all generations or is it subject to gen8 only?

**Comment by Zarel** [comment]
> also i am having a hard time validating teams that are in export format as when i try to import to Json, the objects do not fill in correctly or i get errors... but i can make another issue for that.

This issue is fine. I'm going to need more information about your problem, though. What are you trying to do, and what do the errors look like? Do the errors tell you what's wrong?

> regarding team validation, does this work for all generations or is it subject to gen8 only?

It works for all supported formats in all generations.

**Comment by monsanto** [comment]
Old issue, no response to followup.
