### ISSUE TITLE
Pokemon Showdown thinks my home internet connection is a proxy

### ISSUE THREAD

**Issue by KorinFlakes** [smogon/pokemon-showdown#8395]
Whenever I try to join I get the following message Your IP (xxx.xxx.xxx.xxx) is currently locked due to being a proxy. I do not use a proxy or a VPN and I get this message on all devices in my house (even my mobile). I've even tried rebooting my modem to no avail. I attempted to contact staff in app but was told "regardless you appear to be using a proxy", which again I am not. At this point I literally cannot play Showdown at all.

**Comment by Zarel** [comment]
Some people have a proxy installed somewhere that's hard to find; some home internet connections use the same connections proxies use and are categorized as a proxy.

If you've appealed to staff and they don't unlock you, that means your IP has been abused by spammers or attackers too much for us to unlock you. Sorry, but there's nothing else that can be done about that.
