### ISSUE TITLE
Question: Does the Sim have an undo action/ back step feature?

### ISSUE THREAD

**Issue by nacharya114** [smogon/pokemon-showdown#8409]
For the purposes of creating a bot using Monte carlo methods, I was wondering if the sim ever has/ would consider having a back step feature that retains the seed state for back propogation and exploration. If not, can I contribute here, or should I make my own fork?

**Comment by Zarel** [comment]
We should probably document inputlogs so we don't keep getting these questions.

Anyway: Players can undo turns by exporting an inputlog and deleting the last turn from it.

For better performance when implementing AIs, you would have to serialize the battle every turn, and then deserialize a previous turn to undo.

Storing only the seed isn't enough, you need all battle state to be stored to properly implement undo.

In any case, feel free to contribute code to make this easier.

**Comment by monsanto** [comment]
No response.
