### ISSUE TITLE
Light of Ruin listed as a non-existent move in Gen 8

### ISSUE THREAD

**Issue by InvalidOS** [smogon/pokemon-showdown#8413]
I noticed that Light of Ruin is listed as being illegal when I try to put it on Clefable in Gen 8 STABmons, with the verifier claiming the following:
- Clefable's move Light of Ruin does not exist in Gen 8.
- Clefable can't learn Light of Ruin.

Both Bulbapedia and Serebii seem to suggest otherwise. [The Bulbapedia page](https://bulbapedia.bulbagarden.net/wiki/Light_of_Ruin_(move)) shows a normal description for the move in Sword and Shield, along with listing Max Move power for it on the pages for [Max Starfall](https://bulbapedia.bulbagarden.net/wiki/Max_Starfall_(move)) and [G-Max Smite](https://bulbapedia.bulbagarden.net/wiki/G-Max_Smite_(move)). Serebii's [Gen 8 AttackDex page for Light of Ruin](https://www.serebii.net/attackdex-swsh/lightofruin.shtml) also shows a max move power for Light of Ruin, and also shows a normal description rather than the description saying the move can't be used. Compare that to the page for [Sparkly Swirl](https://www.serebii.net/attackdex-swsh/sparklyswirl.shtml), where it does show the description saying the move can't be used, and a max move power is not shown.

It might be best to do our own research here, given that Light of Ruin is a very strong attack that would almost certainly impact some OMs such as STABmons.

**Comment by Marty-D** [comment]
https://www.smogon.com/forums/posts/8289652/ In Light of Ruin's case, this didn't change in either DLC. Having a normal description never meant anything; what matters is whether the game has the "this move is usable" flag set.

As of DLC2, the list of unusable moves is
`
Karate Chop, Double Slap, Comet Punch, Razor Wind, Jump Kick, Rolling Kick, Twineedle, Sonic Boom, Dragon Rage, Meditate, Rage, Barrier, Bide, Mirror Move, Egg Bomb, Bone Club, Clamp, Spike Cannon, Constrict, Barrage, Bubble, Dizzy Punch, Flash, Psywave, Hyper Fang, Sharpen, Sketch, Spider Web, Nightmare, Feint Attack, Foresight, Return, Frustration, Magnitude, Pursuit, Hidden Power, Smelling Salts, Assist, Refresh, Snatch, Secret Power, Camouflage, Tail Glow, Mud Sport, Ice Ball, Needle Arm, Odor Sleuth, Silver Wind, Grass Whistle, Signal Beam, Sky Uppercut, Water Sport, Psycho Boost, Miracle Eye, Wake-Up Slap, Natural Gift, Embargo, Trump Card, Heal Block, Wring Out, Lucky Chant, Me First, Punishment, Heart Swap, Mud Bomb, Mirror Shot, Rock Climb, Magnet Bomb, Captivate, Chatter, Judgment, Heal Order, Dark Void, Seed Flare, Ominous Wind, Telekinesis, Flame Burst, Synchronoise, Chip Away, Sky Drop, Bestow, Heart Stamp, Steamroller, Relic Song, Rototiller, Ion Deluge, Hyperspace Hole, Powder, Light of Ruin, Hyperspace Fury, every Z-Move, Ice Hammer, Spotlight, Toxic Thread, Revelation Dance, Beak Blast, Zippy Zap, Splishy Splash, Floaty Fall, Pika Papow, Bouncy Bubble, Buzzy Buzz, Sizzly Slide, Glitzy Glow, Baddy Bad, Sappy Seed, Freezy Frost, Sparkly Swirl, Veevee Volley
`
