### ISSUE TITLE
Is there a description or example of Config.usesqlite?

### ISSUE THREAD

**Issue by Starmys** [smogon/pokemon-showdown#8420]
```
Config.usesqlite
Config.usesqlitemodlog
Config.usesqlitefriends
```
How should I set these values and what will be the impact?

**Comment by mia-pi-git** [comment]
> Config.usesqlite
Boolean, turns on uses of SQLite (& ensures SQLite is installed on startup). The respective features that use `useqlitemodlog` and `usesqlitefriends` also check this to ensure we have SQLite enabled and installed.
> Config.usesqlitemodlog
Boolean, enables logging of modlogs to a SQLite database.
> Config.usesqlitefriends
GroupSymbol or undefined, set it to a rank to turn on the friends list (though it will only let that rank and above use said friends list.)

**Comment by Zarel** [comment]
Are these not documented in config-example? They probably should be.
