### ISSUE TITLE
uhtml img tag requires double quotes now

### ISSUE THREAD

**Issue by Hippopotas** [smogon/pokemon-showdown#8428]
It looks like with #8425 , img src now breaks on single quotes. Is this intended behavior?

These work:
```
/adduhtml test, <center><img src="https://i.imgur.com/c9nyFqJ.png" width=330 height=250 ></center>
/adduhtml test, <center><img src=https://i.imgur.com/c9nyFqJ.png width=330 height=250 ></center>
```

This does not work:
```
/adduhtml test, <center><img src='https://i.imgur.com/c9nyFqJ.png' width=330 height=250 ></center>
```
and returns error `Image URLs must begin with 'https://' or 'data:'; 'http://' cannot be used.`

**Comment by mia-pi-git** [comment]
Found the bug. The regex we use to check `src` attribs only checked for tags using "", so tags using '' had the ``''`` included as part of the URI we validated. Hence, it would see a link start with `'https://`, which it doesn't have a case for.
I fixed that [here](https://github.com/smogon/pokemon-showdown/commit/e9f906e5f0b530e44dd7f5fe98bcd907268efb3e).
