### ISSUE TITLE
Awaited Chat.databaseReadyPromise, but Chat.database is still falsy

### ISSUE THREAD

**Issue by vs1720** [smogon/pokemon-showdown#8435]
I tried using node to run a showdown server locally, but I get this error at ...\server\chat-plugins\trivia\database.ts:552:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

Reverting to the new-challenges branch from 3 months ago resolves this issue (that was the most recent branch I found). Just wondering what I can do to fix this, since the issue seems to arise from the trivia folder, which is not there in the old branch.

**Comment by AnnikaCodes** [comment]
Hm, it shouldn't crash when SQLite is disabled. For future reference, the Trivia folder used to be one file: `server/chat-plugins/trivia.ts`.

Anyway, I've pushed a fix—does your server still crash after pulling the latest master?

**Comment by vs1720** [comment]
No crash! Thank you for the fix
