### ISSUE TITLE
How to access simulated stream from other languages?

### ISSUE THREAD

**Issue by vs1720** [smogon/pokemon-showdown#8436]
I was reading the docs and saw that "The stream can also be accessed from other programming languages using standard IO."

My goal is to be able to load states from the middle of a battle and have seen that this is possible using deserialize or exporting the input log. However, I have trouble accessing the stream using the code [here](https://github.com/smogon/pokemon-showdown/blob/master/sim/SIMULATOR.md). I make it a ts file and run it via the command-line, but no more than one turn is executed. 

I can get the cmd interface to work of course, however, re-inputting my inputs gives different outcomes in terms of the damage rolls. So I was wondering how exactly I can run the stream using typescript, then input into the stream with python and read output exactly, since the stream seems to close. 

Thank you! 

EDIT: I was able to figure out how to use the commandline API to replicate non-random battles exactly (I had missed the seed in the documentation.) But I would still appreciate guidance on how to integrate python and typescript and how to replicate random battles since the same seeds generate different teams

**Comment by vs1720** [comment]
I was able to figure it all out

**Comment by Zarel** [comment]
Neat! Yeah, how to stream standard IO depends on the specific language. Most languages should have tutorials if you google 
"[language name] subprocess standard io". But if you have example code you'd like to contribute to our docs, that'd be pretty cool!

**Comment by vs1720** [comment]
Hey! So the issue ends up being that, IO with the command-line API is too slow for my purposes. LoadJSON works great, but obviously cannot be accessed from another language. There is no way to serialize battles from within commandline right?

**Comment by Zarel** [comment]
Unfortunately, not right now. We could add one, though.

**Comment by profmori** [comment]
Did this ever get implemented - I can't see anything in the documentation but I'm not super familiar with JS
