### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by derkaczda** [smogon/pokemon-showdown#8437]
Hello, I am working on a pokemon agent with showdown as the server backend. 
For some time now I am not able to login from a specific PC, getting "Wrong password". But the same username
and password combination works on other machines without any problems. Even stranger the same authentication worked
couple of days ago still on the problematic machine.
My colleague and I heavily played the game with our agent over the last couple of days/weeks, may it be that
we got banned or something like that? 

P.S.: we use the showdown server locally in a Docker container and basically only communicate to the live server (play.pokemonshowdown.com/action.php) for login requests.

![image](https://user-images.githubusercontent.com/34837801/129746386-ae99d061-6a60-4632-b335-f78204fc1439.png)

**Comment by JADcooler** [comment]
ya

**Comment by Zarel** [comment]
@darkaczda, you hit a hacking prevention mechanism. If you're still available, this is a problem that we'll need to resolve privately. Please reach out at `staff@pokemonshowdown.com`

**Comment by derkaczda** [comment]
No it's no longer needed the project has already ended, but thanks good to know for the future.
