### ISSUE TITLE
Speed Boost Not Triggering

### ISSUE THREAD

**Issue by hreine2** [smogon/pokemon-showdown#8470]
On the main PS server, a Ninjask with speed boost seemed not to trigger at end of turn.

Replay: https://replay.pokemonshowdown.com/gen8randombattle-1417316563

Screenshot of set: https://imgur.com/MI64fpk

And as an aside, the Ninjask set did not have an item. None of the documentation seemed to indicate whether or not this was normal but it's something I haven't experienced before so I figured I'd mention it. Appreciate the work you all do!

**Comment by PartMan7** [comment]
Speed Boost is unique in that it needs to have been on the field for the full turn to activate - since you switched out a Pokemon and switched in Ninjask, Speed Boost didn't proc on that turn. Almost no other end-of-turn effect has this behavior, so no, it's not a bug! :D
