### ISSUE TITLE
Gale Wings not working in Multibility OMotM

### ISSUE THREAD

**Issue by HiTechFlufi** [smogon/pokemon-showdown#8485]
In October's Omotm, Multibility, I played a game on the ladder where my opponent had full HP and Gale Wings as their ability in the item slot, yet I still moved first with a 0 priority move. Here is a replay to show it in action: https://replay.pokemonshowdown.com/gen8multibility-1427640304-lvrio7hfboi9lh4gsi9lzqjfpn460azpw

**Comment by mia-pi-git** [comment]
We're aware and are working to deploy a fix. In the future, please put bugs in our bugs thread (https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/)
