### ISSUE TITLE
Zacian listed as an Uber in NPM package

### ISSUE THREAD

**Issue by TeamEnlighten** [smogon/pokemon-showdown#8515]
![Screenshot 2021-11-02 215322](https://user-images.githubusercontent.com/87457810/140012190-25763183-b33f-456d-9af0-a3c355b3eca8.png)
![Screenshot 2021-11-02 215651](https://user-images.githubusercontent.com/87457810/140012193-b48026aa-3e7b-428f-bc89-992f3a312cec.png)

Zacian-Hero is listed as an Uber instead of AG.

**Comment by DaWoblefet** [comment]
Are you on latest master? It's marked correctly here: https://github.com/smogon/pokemon-showdown/blob/dcb20651160836e15836aac795a9bd021906719c/data/formats-data.ts#L6002

**Comment by Zarel** [comment]
Oh, this is about the NPM package being outdated. I haven't gotten around to making sure it all works since the `ts-node` refactor.

**Comment by TeamEnlighten** [comment]
Ok, no worries. I will be patient and if anything clone the master instead 👍

**Comment by c0d3rman** [comment]
Bumping this. Hisui Pokemon are not on the npm package either.

**Comment by yourboid** [comment]
![123](https://user-images.githubusercontent.com/105564423/168446653-2ece3adc-ef64-400f-98ea-1929bf487438.jpg)

**Comment by monsanto** [comment]
The NPM package is way outdated and I'm not interested in maintaining it, so I am closing this.

**Comment by TeamEnlighten** [comment]
I will stick to the master package on Github then. Thank you <3
