### ISSUE TITLE
Visual Glitch: /addhtmlfaq is displayed as /addfaq

### ISSUE THREAD

**Issue by Dirain1700** [smogon/pokemon-showdown#8555]
In Room Faqs(**Raw Text**), /add htmlfaq is displayed as /addfaq.
This wasn't happen the day before yesterday, but it was happen yesterday.
Note: Permission is allowed.(In Japanese Room, @&# can use /addhtmlfaq.)
<img src="https://user-images.githubusercontent.com/86363603/144797030-34bc110d-6be3-43ae-8bd6-a26c4b1f2165.jpeg" width="240px">

**Comment by mia-pi-git** [comment]
This isn't a bug - sources always show /addfaq. Additionally, bugs should be going [here](https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/) in the future.

**Comment by Dirain1700** [comment]
ok sorry.

**Comment by Zarel** [comment]
@mia-pi-git Why isn't this a bug? This seems clearly like a bug and also an easy fix.

**Comment by mia-pi-git** [comment]
It's not a bug because the behavior is just to show the source? I'm only seeing that it shows /addfaq - I don't see how that's a bug.

**Comment by Zarel** [comment]
It's a bug not to show `/addhtmlfaq`.

**Comment by Zarel** [comment]
It already works correctly if you `/viewfaq` a single entry, just not if you `/viewfaq` all of them at once.
