### ISSUE TITLE
How can I set decays in the ladder?

### ISSUE THREAD

**Issue by Starmys** [smogon/pokemon-showdown#8580]
We are going to host a ladder tour in server China and we hope our ladder can decay the scores regularly just like the main server. How does the main server update the scores of all players every day? Do I need to trigger another process to modify the ladder score file?

**Comment by mia-pi-git** [comment]
Hi!
The main sever uses a different setup for ladders - you'll need to either run your own loginserver or manually code in decay to the server, as the current server code has no support for this.

**Comment by Zarel** [comment]
The file is here:

https://github.com/smogon/pokemon-showdown/blob/master/server/ladders-local.ts

**Comment by Zarel** [comment]
I'm closing this because we don't really expect to prioritize the local ladder in any sense, but we would accept PRs to increase how much it can be customized, like to add decay.
