### ISSUE TITLE
Support for various other Glitch Pokemon 

### ISSUE THREAD

**Issue by zurgeg** [smogon/pokemon-showdown#8590]
MissingNo. is supported in Gen I custom battles, but there are other cool Glitch Pokemon out there, like h POKé and PKMNaPKMNゥ ♂ fPKMNk, along with Glitch moves like TM12 and TM37. Additionally, glitch Pokemon aren't limited to Gen I, there is also óË {é Áî/B óË ÁN in Gen III, the Glitch Unown in Gen II, and ----- in Gen IV, etc.,

It'd be cool if these were supported.

**Comment by Zarel** [comment]
You're looking for https://psim.us/suggestions
