### ISSUE TITLE
Impact of Bot matches on User metrics

### ISSUE THREAD

**Issue by curtdissel** [smogon/pokemon-showdown#8604]
Hullo Staff,

I am testing out my Pokemon Showdown server that's specifically for bot matches as we speak.

Since every aspect of Pokemon Showdown is connected, I wanted to discuss the future impact of my server on other areas of showdown.

I reckon my Pokemon Bot Battling Server will become quite popular since I lowered the barrier to entry to create bots.

In this video you can see the output that I generate during a match. It makes it easier for someone to pass the current state of the game to a neural network.

https://vimeo.com/661786118/b702e95a42

Considerations:
Potentially 1000s or 10000s or 100000s of users are created to fight on my server.
How will this impact metrics of user activity and team configurations?
A few bots mixed in with a bunch of a human data isn't an issue.
But many bots could begin to impact metrics such as most used items/pokemon.

If things begin to get out of hands, I think it is worth considering providing a different login server for my bot fights. That way the bot data does not taint the human generated data.

Obviously, none of this is an issue now, but I am preemptively thinking of a solution to a problem I know will come.

**Comment by mia-pi-git** [comment]
> How will this impact metrics of user activity

We only take user activity stats for the main server.

>  and team configurations?

Usage stats data is likewise only taken from main server logs. 
Generally, activity on your side server won't affect main / main's stats.

**Comment by curtdissel** [comment]
Thanks. This is good to know.

**Comment by Zarel** [comment]
Incidentally, PS has a command-line switch `--no-security`, if you'd like to be able to log in without connecting to the loginserver. It lets you log in without a token.

**Comment by curtdissel** [comment]
I will keep that in mind. It would allow I think for people to create a bunch of bots without the added burden of them also creating a bunch of usernames.
