### ISSUE TITLE
winget cannot find pokemon showdown version and always thinks there is an available upgrade

### ISSUE THREAD

**Issue by ix0rai** [smogon/pokemon-showdown#8623]
When installing pokemon showdown through winget, winget always acts as if there is an applicable update to `0.3.0` for it and claims that the current installed version is `Unknown`
![image](https://user-images.githubusercontent.com/66223394/149021215-0683bec2-a9cb-45c6-8baf-c5caa022c7fe.png)

Performing the upgrade does not fix the issue, the version is still `Unknown`

**Comment by ix0rai** [comment]
it seems like this isn't an issue with showdown, it's an issue with winget, sorry to bother you all

**Comment by ix0rai** [comment]
reopening after getting this response after asking on the winget repository:
> It is because pokemon showdown doesn't write displayversion registry key, so winget cannot read it from ARP list. You should ask the developer of pokemon showdown to make their installer write this key.

**Comment by ix0rai** [comment]
Could this issue be transferred to the showdown client?

**Comment by ix0rai** [comment]
small update: I'm not using windows anymore, which would make it quite a bother to test this issue
I'm no longer going to be any help if someone wants to look into fixing this

**Comment by monsanto** [comment]
Creator is no longer interested & I am also not interested in maintaining the .exe
