### ISSUE TITLE
Infinite loop on login screen glitch

### ISSUE THREAD

**Issue by pls-dont-judge-me-uwu** [smogon/pokemon-showdown#8788]
![1E86850F-3964-4066-A11A-B94170F5E61F](https://user-images.githubusercontent.com/106033497/169712382-3f6dd890-58dd-4f64-8e3f-5b1df51bcc25.GIF)

**Comment by mia-pi-git** [comment]
This is not a bug. Though, since the appeal link goes to helptickets we should be changing it to [here](https://www.smogon.com/forums/threads/discipline-appeal-rules.3583479/).
