### ISSUE TITLE
Friend Requests

### ISSUE THREAD

**Issue by danielobrien3** [smogon/pokemon-showdown#8790]
The majority of my time my friends and I use Showdown is to play each other. Having a friends list would greatly improve our experience. 

I also have some development experience, and if this would be a good first issue I would be happy to take it on.

**Comment by mia-pi-git** [comment]
I did this last summer. Type /friends in any chat to access your list.

**Comment by mia-pi-git** [comment]
Also, in the future, suggestions go [here.](https://www.smogon.com/forums/threads/about-this-forum-read-before-posting.3650597/) 
Have a nice day!

**Comment by danielobrien3** [comment]
Awesome. Thank you had no idea!
