### ISSUE TITLE
[Question] Looking for a Way to Start a Battle from a Particular State

### ISSUE THREAD

**Issue by DHolden24** [smogon/pokemon-showdown#8811]
Hi all!

I'm working on a project that has to do with simulating a bunch of battles. I was wondering if Showdown has a way to take that state of a battle at an arbitrary turn, and then start a new instance of that battle from that turn.

For example, let's say I would like to redo a battle from turn 3 onwards while keeping the first 2 turns as is, while allowing for different rng rolls for going forward.

Does something like this exist in the codebase already? I haven't had much luck finding anything in my digging so far, and figured I'd ask before before I get too far down any rabbit holes. 

Thanks in advance!

**Comment by Slayer95** [comment]
Hi @DHolden24

The ``Battle`` class is compatible with the ``JSON`` APIs, so you may just call ``JSON.stringify()`` on a battle instance to obtain a string which you can then parse with ``Battle.fromJSON(string)``. Then you may call the method ``Battle#resetRNG(null)`` to recreate the PRNG state.

**Comment by DHolden24** [comment]
Hi @Slayer95 
That sounds like exactly what I need, and seems pretty straight forward! Thanks for the pointer!

**Comment by DHolden24** [comment]
I've gotten something working, no further questions at this point.
Thanks again for your help Slayer!
