### ISSUE TITLE
File request

### ISSUE THREAD

**Issue by kokoukohiro** [smogon/pokemon-showdown#8995]
For research purposes, I need to access the play.pokemonshowdown.com/logs directory to obtain more detailed and complete data for AI training. Anyone can provide me with a copy of the logs directory, or a permission to access it?

**Comment by HoeenCoder** [comment]
Absolutely not. Your asking for hundreds of gigabytes of information including chat logs and battle logs. This would leak people's teams (many professional VGC players use PS to practice) and leak all sorts of conversations, including very private ones (arguably personal information).

Make a data request instead by emailing staff@pokemonshowdown.com . Please make sure to tell us why you want the data and what data specifically you want (not "all of it"). An admin who manages grants will speak with you after that. Please note were extremely busy with Gen 9's release so we might not get to your request for a while.
