### ISSUE TITLE
Json serialise the battle state in the request that each player gets

### ISSUE THREAD

**Issue by spktrm** [smogon/pokemon-showdown#9014]
Feature request to serialise all public and private information about the battle directly from battle object and have it made available to the player in the request json.

If an application would like to use this information, currently they would need to track it from input logs and recreate complex battle logic to parse messages. Since showdown already does this, why not include this information in the request?

**Comment by mia-pi-git** [comment]
Chiefly, this would be a massive information leak if we included private info and would provide significant competitive advantage if someone modified a client. 
If we didn't include private info, that's still a lot of extra bandwidth - battle states are big.

**Comment by spktrm** [comment]
Let me clarify; by private information I mean information about the state of the game that only the player should know. Public is information that both the player and opponent know.
