### ISSUE TITLE
Order Up Mechanism & Description Issue

### ISSUE THREAD

**Issue by Starmys** [smogon/pokemon-showdown#9120]
- Mechanism: in NS Pokemon S/V, order up boosts the user's stat even if it is protected.
- [Description](https://bulbapedia.bulbagarden.net/wiki/Order_Up_(move)#Effect): +1 to stat depending on Tatsugiri form, not color.

**Comment by DaWoblefet** [comment]
The functionality was fixed in https://github.com/smogon/pokemon-showdown/pull/9180. Anyone else is free to update the short desc.
