### ISSUE TITLE
Gen 9 Nat Dex numbers currently used in pokedex.ts does not match Serebii's and confirmed TCG info

### ISSUE THREAD

**Issue by JohnEstropia** [smogon/pokemon-showdown#9151]
For example, [Smoliv is currently declared as `935`](https://github.com/smogon/pokemon-showdown/blob/master/data/pokedex.ts#L16964), but have [confirmed National Dex Number `0928`](https://www.pokemon-card.com/products/2022/images/1501_C005_0928MINIVE.png).
[Serebii seems to have this correct](https://serebii.net/card/dex/928.shtml) as well.

**Comment by KrisXV** [comment]
This is known and there’s even an open pull request to fix it. Please be patient while we update the other aspects of the simulator and client that rely on these dex numbers https://github.com/smogon/pokemon-showdown/pull/9140

**Comment by JohnEstropia** [comment]
Thanks, and sorry if I missed the related PR
