### ISSUE TITLE
Tauros naming inconsistency

### ISSUE THREAD

**Issue by Glazelf** [smogon/pokemon-showdown#9367]
In the usage statistics Tauros forms are named Tauros-Paldea-Water and Tauros-Paldea-Fire, while on the actual Showdown website, they are called Tauros-Paldea-Aqua and Tauros-Paldea-Blaze.
![image](https://user-images.githubusercontent.com/35176230/215293442-cdc8c13d-f144-4c26-b95e-b8799746d2a9.png)
![image](https://user-images.githubusercontent.com/35176230/215293464-05c99c44-2838-4081-b7a2-875fdf509783.png)

**Comment by Marty-D** [comment]
This rename happened last week; the next set of usage stats in a few days will have the new names too.
