### ISSUE TITLE
Revealing OTS info on hover

### ISSUE THREAD

**Issue by Glazelf** [smogon/pokemon-showdown#9389]
I feel like OTS-revealed information should be visible on hovering over Pokémon instead of what actually has been used in that battle, given ofcourse that OTS was accepted by both players.

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232964397-8cefa89b-4a70-41f1-9d8f-915a63bf94a3.png)

**Comment by Zarel** [comment]
OTS?

**Comment by Glazelf** [comment]
> OTS? What's that?

I was referring to Open Team Sheets! 
If it's accepted, I think the relevant info could also be enabled in the information bubbles that show when you hover over a Pokémon during battle.

**Comment by Glazelf** [comment]
This was added in d3cb797867d4872e7cbaa44e8bd842478bde0a5d.
Closing this issue, thanks a lot Karthik!
