### ISSUE TITLE
[feature-request] Support for Random VGC-like Battles in Gen9

### ISSUE THREAD

**Issue by DiTo97** [smogon/pokemon-showdown#9390]
Hi @Zarel, @Marty-D,

Pokémon Showdown is great, and I love it, but I always wondered why you support only single random battles, double random battles, but not double random battles VGC-style. I'm not staying following the actual VGC metagame, it could still follow the same rules of double random battles, but just a random setting with the bring-six-take-4 dynamic. It may seem like a minor integration, but that dynamic is one of the major pillars of the VGC format, and having a random format integrating it could be a valuable resource for casual players that may be used to the 6v6 random doubles setting, to learn the matchup-specific and end goal reward dynamics that the take-four rule introduces.

Moreover, as random battles are one of the main means of training Pokémon battle bots to learn the dynamics of a Pokémon battle, having a VGC-like double randoms setting could go a long way in enabling VGC battle bots, which have historically been lacking.

Let me know your thoughts!

**Comment by PartMan7** [comment]
Uhh don't custom battle rules already allow you to do this? (maxteamsize=6, pickedteamsize=4, team preview)

**Comment by DiTo97** [comment]
> Uhh don't custom battle rules already allow you to do this? (maxteamsize=6, pickedteamsize=4, team preview)

I completely forgot about custom rules! Even then, do they allow for random battles, as I think that's the glue of the whole thing?

**Comment by PartMan7** [comment]
Try DMing a friend `/challenge gen9randombattle @@@ pickedteamsize=4, maxteamsize=6, teampreview`

**Comment by DiTo97** [comment]
> Try DMing a friend `/challenge gen9randombattle @@@ pickedteamsize=4, maxteamsize=6, teampreview`

That works for me. Thanks @PartMan7!

I also tried `gen9randomdoublebattle`, but that resulted in a wrong format error. Does the Gen9 random doubles formats have a different code, or is it not yet supported?

**Comment by PartMan7** [comment]
I don't think the format exists in doubles yet, sadly... You can always try gen8, though!

**Comment by DiTo97** [comment]
For future reference, the full command waiting for Gen 9 support is the following:
`/challenge gen8randomdoublesbattle @@@ maxlevel=50, maxteamsize=6, pickedteamsize=4, teampreview, vgctimer`

**Comment by DiTo97** [comment]
After further testing, I noticed that level down args (e.g., `maxlevel`, `adjustlevel`, `adjustleveldown`) do not work properly.

Is it because of the random format, @PartMan7? Is there any way to enforce the level 50 constraint?
