### ISSUE TITLE
Support for Gen 9 random doubles

### ISSUE THREAD

**Issue by DiTo97** [smogon/pokemon-showdown#9391]
Hi @Zarel, @Marty-D,

Is there a timeline for Gen 9 random doubles, which are currently not supported?

**Comment by mia-pi-git** [comment]
Hi! There is currently no ETA on this - making sets takes a while, and the metas need to stabilize more first.
In the future, simple questions like this are better suited to [this thread](https://www.smogon.com/forums/threads/ask-simple-questions-here-read-original-post-before-posting.3520646/page-123#post-9492231).
Have a nice day!

**Comment by DiTo97** [comment]
Sorry, I am not that familiar with Smogon yet. Thanks for sharing the link!
