### ISSUE TITLE
Gen 8 still default

### ISSUE THREAD

**Issue by profmori** [smogon/pokemon-showdown#9406]
When trying to run a battle in Gen 9 OU using the offline JS library, a battle format does not seem to exist.

Running `>start {"formatid":"ou"}` defaults to gen 8, and running `>start {"formatid":"gen9ou"}` runs the game in a format that does not exist (the `exists` variable is False).

**Comment by joebangara43903** [comment]
![image](https://user-images.githubusercontent.com/131228993/232964242-34cbd0ca-6c17-4651-9079-e7e0a08ffe23.png)

**Comment by Zarel** [comment]
Sorry, our NPM package was outdated. The latest version should work correctly.
