### ISSUE TITLE
How to obtain a SSL certificate for a registered server

### ISSUE THREAD

**Issue by Starmys** [smogon/pokemon-showdown#9464]
This may be a very stupid question, but there seems no way to get a SSL certificate of ```foo.psim.us``` through Let's Encrypt.

I noticed that ```smogtours.psim.us```, ```dawn.psim.us``` and ```podown.psim.us``` share a Cloudflare SSL certificate. What should I do to get this certificate for another registered server?

**Comment by urkerab** [comment]
Your certificate needs to be for the computer running the server itself rather than the client. For instance in your example of `dawn.psim.us` this is `server.dawn-ps.com`.
