### ISSUE TITLE
Shadow tag does not always prevent switching 

### ISSUE THREAD

**Issue by jcreek** [smogon/pokemon-showdown#9482]
In turn 4 of [this match](https://replay.pokemonshowdown.com/gen9vgc2023series2-1831491953) my opponent's Pokémon are both able to switch out, despite having Shadow Tag in play.

**Comment by adrivrie** [comment]
Ghost pokemon cannot be trapped. This sort of bug report is likely better placed on the smogon bug thread, the first post of which lists this issue as a frequent not-bug: https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8455372
