### ISSUE TITLE
Regulation E Bo3  Matches Continue Even After One Person Disconnects in the First Game

### ISSUE THREAD

**Issue by DHolden24** [smogon/pokemon-showdown#9819]
It seems that if one person disconnects from a Bo3 at the end of a game (possibly before the end, but I haven't encountered that issue), the subsequent game(s) continue as if they had selected that they're ready for the next battle.

During the next battles, the person who didn't disconnect is forced to play it out while the other "player" times out on every turn.
This is incredibly frustrating and seems to be easily griefable (to be clear, I'm not saying I think my opponent griefed me in the case below).

Example Case:
Game 1: https://replay.pokemonshowdown.com/gen9vgc2023regulationebo3-1958948526
- Glueckskaefer disconnects at the end of the game
- Seemingly disconnects before hitting the "I'm Ready" button for the next game

Game 2: https://replay.pokemonshowdown.com/gen9vgc2023regulationebo3-1958951624
- Glueckskaefer times out every turn as they are seemingly not connected and presumably never even joined the game

Not sure if it's helpful, but here's the Bo3 Room: https://play.pokemonshowdown.com/game-bestof3-gen9vgc2023regulationebo3-1958948525

This has happened in other cases to me as well. In one of them, I looked up the player and they were listed as offline for the duration of the 2nd and 3rd battles.

**Comment by chouettevan** [comment]
None of the rooms exist.you didn't save the replays.

**Comment by DHolden24** [comment]
I'm pretty sure I did, they may have gotten lost and not recovered yet with the replay issues, but I have no way of knowing for sure  one way or the other.
https://x.com/PokemonShowdown/status/1729994174106095649?s=20
https://x.com/PokemonShowdown/status/1732171533416792250?s=20

Regardless, the bug shouldn't be too bad to reproduce. From what I could gather, it only requires one player disconnect at the end of one of the Bo3 games while there are still more to be played

**Comment by Zarel** [comment]
Fixed by 514017934bcaa351f750
