### ISSUE TITLE
Homepage link not working 

### ISSUE THREAD

**Issue by gayatriagarwal19** [smogon/pokemon-showdown#9829]
Homepage link on the battle page is not working 

To recreate the issue:
1- click on "play online" on homepage
2- try to click on the home link in navbar indicated below, it is not clickable.
 
![Showdown! - Google Chrome 09-10-2023 00_00_22](https://github.com/smogon/pokemon-showdown/assets/98116507/d45956a0-36bf-4230-b7d5-a2cbac30e2ce)

Please assign me this issue, I would like to work on it.

**Comment by monsanto** [comment]
Thanks for offering to help, but this isn't a bug. Try opening the teambuilder and you'll see what that home tab is for
