### ISSUE TITLE
Open team sheets not appearing in best of 3 match on ladder

### ISSUE THREAD

**Issue by Mut-antVGC** [smogon/pokemon-showdown#9881]
Today I have experienced a new bug occurring in my best of 3 matches on the ladder, that caused a lot of error messages to appear and importantly causing the team sheets not to show up. I have a few screenshots of my last match that has been affected by this. 
![Schermopname (31)](https://github.com/smogon/pokemon-showdown/assets/149900545/166eaf27-e734-4864-87ab-54d2f15df644)
![Schermopname (32)](https://github.com/smogon/pokemon-showdown/assets/149900545/97ff0d2e-0e5e-496e-9bd5-26ed8e2918b6)
![Schermopname (33)](https://github.com/smogon/pokemon-showdown/assets/149900545/b6f83942-cca5-4d73-97bf-2a4dda0d4897)
I have also noticed a slight offset in chat messages that might be related to this issue since I have only seen it happen in matches with this issue. In the image below is an example of this chat offset.
![Schermopname (34)](https://github.com/smogon/pokemon-showdown/assets/149900545/8fc48216-12a7-4898-b3b8-8e08490fa81f)
Personally I wouldn't know how this issue could happen and how the chat offset seems to be a byproduct of this bug, but I am not very familliar with pokémon showdown's code either. 
Anyways I felt that this was a kind of bug worth reporting since it affects the gameplay and while all my opponents were friendly enough to use the command !showteam, I think that this bug is still noteworthy.

**Comment by DaWoblefet** [comment]
This would have been a client bug from the new server protocol implemented for OTS in tooltips. Sometimes cache busting sucks, but I'm sure it's fixed by now for you.
