### ISSUE TITLE
Eu não sei a senha da minha conta 

### ISSUE THREAD

**Issue by Playerjuniordbr** [smogon/pokemon-showdown#9922]
Eu tenho a minha conta que é playerjuniordbr eu sempre uso a mesma senha porem esse nome eu tinha a senha diferente que eu sei  e eu não sei qual é a senha a qual eu tinha colocado 
Uma sugestão que eu queira é colocar uma opção que mudaria a senha da conta que isso ajudaria muitas pessoas que registraram o nome

**Comment by Zarel** [comment]
Duplicate of https://github.com/smogon/pokemon-showdown-client/issues/972
