### ISSUE TITLE
Changing Teams Mid-Battle (ie. Gaining EVs, leveling up, etc)

### ISSUE THREAD

**Issue by PSMusicalRoc** [smogon/pokemon-showdown#9939]
Hi! This is probably going to sound like a dumb question, but is there anything currently set in place to alter certain parts of teams during battle? I'm trying to create the basis of a "standard" battle from mainline games (ie. EXP, leveling up, gaining EVs), and that functionality would add a lot of accuracy to my battler.

**Comment by Zarel** [comment]
Currently that would require a manual `eval`.
