### ISSUE TITLE
Add "Copy to Clipboard" button to replay modal

### ISSUE THREAD

**Issue by jmynes** [smogon/pokemon-showdown#9953]
A button here that copies to the clipboard would be hugely appreciated when reporting tournament matches:
![image](https://github.com/smogon/pokemon-showdown/assets/15176546/62f56102-0911-4023-bdf7-5083c37e0962)

Even better, putting a button here that does upload + share + copy would be even more convenient:
![image](https://github.com/smogon/pokemon-showdown/assets/15176546/fdde1e61-d645-4fa6-b7ec-ce802737c29f)

The current behavior where it doesn't copy to clipboard by default when clicking `Upload and share replay` is also appreciated, though, so please do not make automatic link copying the _only_ option

**Comment by mia-pi-git** [comment]
Looks like Zarel forgot to add this functionality back when he moved the popup to the server, so I added a button that'll do the same thing as it used to (after a restart.) In the future, both suggestions and bugs (of which this is one) would go in the PS forum on Smogon.

**Comment by jmynes** [comment]
Apologies for the necrobump, the button is active but isn't actually copying to my clipboard

Tested on Microsoft Edge for Win 10 in incognito
